In [4]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 

import seaborn as sns

In [13]:
pd.set_option('max_columns', None)

In [14]:
df = pd.read_csv("D:/Hackathon2022/Decarbonising_Supply_Chain/Data/1. Mandata Vehicle Summary.csv")
df

,REG,DATE,START,END,DRIVING_TIME,DRIVE_PERC,IDLE_TIME,IDLE_PERC,STANDING_TIME,STANDING_PERC,INACTIVE_TIME,INACTIVE_PERC,UTILISATION,UTILISATION_PERC,JOURNEYS,MILES,KM,GALLONS,LITRES,MPG,L_100KM,ODOMETER_START,ODOMETER_END
0,DX66OYU,26/05/2021,2021-05-26 12:33:00,2021-05-27 01:00:00,05:57:59,24.86,00:00:16,0.02,06:28:29,26.98,11:33:16,48.14,12:26:44,51.86,59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,593088.25
1,DX66OYU,27/05/2021,2021-05-27 01:00:00,2021-05-27 18:09:00,06:26:42,26.85,00:01:18,0.09,10:41:05,44.52,06:50:55,28.54,17:09:05,71.46,43,164.16,264.19,18.95,86.13,8.66,32.60,593088.25,593352.44
2,DX66OYU,28/05/2021,2021-05-28 06:54:00,2021-05-28 20:19:00,08:38:19,35.99,00:00:02,0.00,04:45:55,19.86,10:35:44,44.15,13:24:16,55.85,19,316.42,509.23,37.45,170.24,8.45,33.43,593352.44,593861.67
3,DX66OYU,01/06/2021,2021-06-01 06:54:00,2021-06-02 00:46:00,08:29:09,35.36,00:00:57,0.07,09:21:41,39.01,06:08:13,25.57,17:51:47,74.43,48,282.48,454.61,31.39,142.72,9.00,31.39,593861.67,594316.27
4,DX66OYU,02/06/2021,2021-06-02 06:25:00,2021-06-02 18:24:00,04:34:05,19.03,00:00:00,0.00,07:24:37,30.88,12:01:18,50.09,11:58:42,49.91,35,84.36,135.77,12.99,59.07,6.49,43.51,594316.27,594452.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4494,YM17NCA,22/12/2021,2021-12-22 07:00:00,2021-12-23 00:00:00,03:59:07,16.61,00:12:24,0.86,12:47:56,53.33,07:00:33,29.20,16:59:27,70.80,23,78.66,126.59,15.65,71.15,5.03,56.20,477036.90,477163.49
4495,YM17NCA,23/12/2021,2021-12-23 00:00:00,2021-12-23 15:05:00,04:51:23,20.23,00:00:00,0.00,10:14:34,42.68,08:54:03,37.09,15:05:57,62.91,30,101.85,163.91,13.96,63.47,7.30,38.72,477163.49,477327.39
4496,YM17NCA,24/12/2021,2021-12-24 11:22:00,2021-12-24 11:24:00,00:01:02,0.07,00:00:00,0.00,00:01:10,0.08,23:57:48,99.85,00:02:12,0.15,1,0.05,0.09,0.03,0.15,1.64,172.94,477327.39,477327.48
4497,YM17NCA,30/12/2021,2021-12-30 13:10:00,2021-12-30 14:20:00,00:00:00,0.00,00:36:23,2.53,00:34:05,2.37,22:49:32,95.11,01:10:28,4.89,0,0.00,0.00,0.42,1.92,0.00,0.00,477327.48,477327.48
4498,YM17NCA,31/12/2021,2021-12-31 08:42:00,2021-12-31 12:06:00,00:27:24,1.90,00:36:05,2.51,02:20:38,9.77,20:35:53,85.83,03:24:07,14.17,10,2.44,3.92,0.85,3.88,2.85,99.03,477327.48,477331.40

In [15]:
df = df.dropna()
df = df.reset_index(drop = True)
df

,REG,DATE,START,END,DRIVING_TIME,DRIVE_PERC,IDLE_TIME,IDLE_PERC,STANDING_TIME,STANDING_PERC,INACTIVE_TIME,INACTIVE_PERC,UTILISATION,UTILISATION_PERC,JOURNEYS,MILES,KM,GALLONS,LITRES,MPG,L_100KM,ODOMETER_START,ODOMETER_END
0,DX66OYU,27/05/2021,2021-05-27 01:00:00,2021-05-27 18:09:00,06:26:42,26.85,00:01:18,0.09,10:41:05,44.52,06:50:55,28.54,17:09:05,71.46,43,164.16,264.19,18.95,86.13,8.66,32.60,593088.25,593352.44
1,DX66OYU,28/05/2021,2021-05-28 06:54:00,2021-05-28 20:19:00,08:38:19,35.99,00:00:02,0.00,04:45:55,19.86,10:35:44,44.15,13:24:16,55.85,19,316.42,509.23,37.45,170.24,8.45,33.43,593352.44,593861.67
2,DX66OYU,01/06/2021,2021-06-01 06:54:00,2021-06-02 00:46:00,08:29:09,35.36,00:00:57,0.07,09:21:41,39.01,06:08:13,25.57,17:51:47,74.43,48,282.48,454.61,31.39,142.72,9.00,31.39,593861.67,594316.27
3,DX66OYU,02/06/2021,2021-06-02 06:25:00,2021-06-02 18:24:00,04:34:05,19.03,00:00:00,0.00,07:24:37,30.88,12:01:18,50.09,11:58:42,49.91,35,84.36,135.77,12.99,59.07,6.49,43.51,594316.27,594452.04
4,DX66OYU,03/06/2021,2021-06-03 07:56:00,2021-06-04 01:00:00,07:59:22,33.29,00:03:13,0.22,09:01:17,37.59,06:56:08,28.90,17:03:52,71.10,34,273.51,440.18,32.25,146.61,8.48,33.31,594452.04,594892.21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4491,YM17NCA,22/12/2021,2021-12-22 07:00:00,2021-12-23 00:00:00,03:59:07,16.61,00:12:24,0.86,12:47:56,53.33,07:00:33,29.20,16:59:27,70.80,23,78.66,126.59,15.65,71.15,5.03,56.20,477036.90,477163.49
4492,YM17NCA,23/12/2021,2021-12-23 00:00:00,2021-12-23 15:05:00,04:51:23,20.23,00:00:00,0.00,10:14:34,42.68,08:54:03,37.09,15:05:57,62.91,30,101.85,163.91,13.96,63.47,7.30,38.72,477163.49,477327.39
4493,YM17NCA,24/12/2021,2021-12-24 11:22:00,2021-12-24 11:24:00,00:01:02,0.07,00:00:00,0.00,00:01:10,0.08,23:57:48,99.85,00:02:12,0.15,1,0.05,0.09,0.03,0.15,1.64,172.94,477327.39,477327.48
4494,YM17NCA,30/12/2021,2021-12-30 13:10:00,2021-12-30 14:20:00,00:00:00,0.00,00:36:23,2.53,00:34:05,2.37,22:49:32,95.11,01:10:28,4.89,0,0.00,0.00,0.42,1.92,0.00,0.00,477327.48,477327.48
4495,YM17NCA,31/12/2021,2021-12-31 08:42:00,2021-12-31 12:06:00,00:27:24,1.90,00:36:05,2.51,02:20:38,9.77,20:35:53,85.83,03:24:07,14.17,10,2.44,3.92,0.85,3.88,2.85,99.03,477327.48,477331.40

In [18]:
df["mileage"] = df["MPG"] * 0.43 
df

,REG,DATE,START,END,DRIVING_TIME,DRIVE_PERC,IDLE_TIME,IDLE_PERC,STANDING_TIME,STANDING_PERC,INACTIVE_TIME,INACTIVE_PERC,UTILISATION,UTILISATION_PERC,JOURNEYS,MILES,KM,GALLONS,LITRES,MPG,L_100KM,ODOMETER_START,ODOMETER_END,mileage
0,DX66OYU,27/05/2021,2021-05-27 01:00:00,2021-05-27 18:09:00,06:26:42,26.85,00:01:18,0.09,10:41:05,44.52,06:50:55,28.54,17:09:05,71.46,43,164.16,264.19,18.95,86.13,8.66,32.60,593088.25,593352.44,3.7238
1,DX66OYU,28/05/2021,2021-05-28 06:54:00,2021-05-28 20:19:00,08:38:19,35.99,00:00:02,0.00,04:45:55,19.86,10:35:44,44.15,13:24:16,55.85,19,316.42,509.23,37.45,170.24,8.45,33.43,593352.44,593861.67,3.6335
2,DX66OYU,01/06/2021,2021-06-01 06:54:00,2021-06-02 00:46:00,08:29:09,35.36,00:00:57,0.07,09:21:41,39.01,06:08:13,25.57,17:51:47,74.43,48,282.48,454.61,31.39,142.72,9.00,31.39,593861.67,594316.27,3.8700
3,DX66OYU,02/06/2021,2021-06-02 06:25:00,2021-06-02 18:24:00,04:34:05,19.03,00:00:00,0.00,07:24:37,30.88,12:01:18,50.09,11:58:42,49.91,35,84.36,135.77,12.99,59.07,6.49,43.51,594316.27,594452.04,2.7907
4,DX66OYU,03/06/2021,2021-06-03 07:56:00,2021-06-04 01:00:00,07:59:22,33.29,00:03:13,0.22,09:01:17,37.59,06:56:08,28.90,17:03:52,71.10,34,273.51,440.18,32.25,146.61,8.48,33.31,594452.04,594892.21,3.6464
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4491,YM17NCA,22/12/2021,2021-12-22 07:00:00,2021-12-23 00:00:00,03:59:07,16.61,00:12:24,0.86,12:47:56,53.33,07:00:33,29.20,16:59:27,70.80,23,78.66,126.59,15.65,71.15,5.03,56.20,477036.90,477163.49,2.1629
4492,YM17NCA,23/12/2021,2021-12-23 00:00:00,2021-12-23 15:05:00,04:51:23,20.23,00:00:00,0.00,10:14:34,42.68,08:54:03,37.09,15:05:57,62.91,30,101.85,163.91,13.96,63.47,7.30,38.72,477163.49,477327.39,3.1390
4493,YM17NCA,24/12/2021,2021-12-24 11:22:00,2021-12-24 11:24:00,00:01:02,0.07,00:00:00,0.00,00:01:10,0.08,23:57:48,99.85,00:02:12,0.15,1,0.05,0.09,0.03,0.15,1.64,172.94,477327.39,477327.48,0.7052
4494,YM17NCA,30/12/2021,2021-12-30 13:10:00,2021-12-30 14:20:00,00:00:00,0.00,00:36:23,2.53,00:34:05,2.37,22:49:32,95.11,01:10:28,4.89,0,0.00,0.00,0.42,1.92,0.00,0.00,477327.48,477327.48,0.0000
4495,YM17NCA,31/12/2021,2021-12-31 08:42:00,2021-12-31 12:06:00,00:27:24,1.90,00:36:05,2.51,02:20:38,9.77,20:35:53,85.83,03:24:07,14.17,10,2.44,3.92,0.85,3.88,2.85,99.03,477327.48,477331.40,1.2255

In [21]:
df.drop(["ODOMETER_START", "ODOMETER_END", "JOURNEYS", "GALLONS", "MPG", "MILES"], axis = 1, inplace = True, errors="ignore")

In [22]:
df

,REG,DATE,START,END,DRIVING_TIME,DRIVE_PERC,IDLE_TIME,IDLE_PERC,STANDING_TIME,STANDING_PERC,INACTIVE_TIME,INACTIVE_PERC,UTILISATION,UTILISATION_PERC,KM,LITRES,L_100KM,mileage
0,DX66OYU,27/05/2021,2021-05-27 01:00:00,2021-05-27 18:09:00,06:26:42,26.85,00:01:18,0.09,10:41:05,44.52,06:50:55,28.54,17:09:05,71.46,264.19,86.13,32.60,3.7238
1,DX66OYU,28/05/2021,2021-05-28 06:54:00,2021-05-28 20:19:00,08:38:19,35.99,00:00:02,0.00,04:45:55,19.86,10:35:44,44.15,13:24:16,55.85,509.23,170.24,33.43,3.6335
2,DX66OYU,01/06/2021,2021-06-01 06:54:00,2021-06-02 00:46:00,08:29:09,35.36,00:00:57,0.07,09:21:41,39.01,06:08:13,25.57,17:51:47,74.43,454.61,142.72,31.39,3.8700
3,DX66OYU,02/06/2021,2021-06-02 06:25:00,2021-06-02 18:24:00,04:34:05,19.03,00:00:00,0.00,07:24:37,30.88,12:01:18,50.09,11:58:42,49.91,135.77,59.07,43.51,2.7907
4,DX66OYU,03/06/2021,2021-06-03 07:56:00,2021-06-04 01:00:00,07:59:22,33.29,00:03:13,0.22,09:01:17,37.59,06:56:08,28.90,17:03:52,71.10,440.18,146.61,33.31,3.6464
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4491,YM17NCA,22/12/2021,2021-12-22 07:00:00,2021-12-23 00:00:00,03:59:07,16.61,00:12:24,0.86,12:47:56,53.33,07:00:33,29.20,16:59:27,70.80,126.59,71.15,56.20,2.1629
4492,YM17NCA,23/12/2021,2021-12-23 00:00:00,2021-12-23 15:05:00,04:51:23,20.23,00:00:00,0.00,10:14:34,42.68,08:54:03,37.09,15:05:57,62.91,163.91,63.47,38.72,3.1390
4493,YM17NCA,24/12/2021,2021-12-24 11:22:00,2021-12-24 11:24:00,00:01:02,0.07,00:00:00,0.00,00:01:10,0.08,23:57:48,99.85,00:02:12,0.15,0.09,0.15,172.94,0.7052
4494,YM17NCA,30/12/2021,2021-12-30 13:10:00,2021-12-30 14:20:00,00:00:00,0.00,00:36:23,2.53,00:34:05,2.37,22:49:32,95.11,01:10:28,4.89,0.00,1.92,0.00,0.0000
4495,YM17NCA,31/12/2021,2021-12-31 08:42:00,2021-12-31 12:06:00,00:27:24,1.90,00:36:05,2.51,02:20:38,9.77,20:35:53,85.83,03:24:07,14.17,3.92,3.88,99.03,1.2255

In [16]:
df["REG"].unique()

array(['DX66OYU', 'DX66PFJ', 'KP63HZR', 'NK17LGD', 'NK17LGE', 'NK17LGF',
       'NK17LGG', 'NK17LGJ', 'NK17LGL', 'NK67LKD', 'NK67LKE', 'NK67LKF',
       'NK67LKX', 'NK67LKY', 'NK67LKZ', 'NK67LLA', 'NK67LLC', 'YM17NCA'],
      dtype=object)

In [17]:
dfTry = df[df["REG"] == "NK17LGF"]
dfTry

,REG,DATE,START,END,DRIVING_TIME,DRIVE_PERC,IDLE_TIME,IDLE_PERC,STANDING_TIME,STANDING_PERC,INACTIVE_TIME,INACTIVE_PERC,UTILISATION,UTILISATION_PERC,JOURNEYS,MILES,KM,GALLONS,LITRES,MPG,L_100KM,ODOMETER_START,ODOMETER_END
1074,NK17LGF,03/01/2021,2021-01-03 11:19:00,2021-01-03 11:31:00,00:05:18,0.37,00:00:00,0.00,00:06:23,0.44,23:48:19,99.19,00:11:41,0.81,1,0.17,0.28,0.20,0.92,0.84,334.55,334983.01,334983.28
1075,NK17LGF,04/01/2021,2021-01-04 04:23:00,2021-01-04 16:17:00,06:18:47,26.30,00:00:00,0.00,05:35:31,23.30,12:05:42,50.40,11:54:18,49.60,21,252.95,407.09,30.50,138.65,8.29,34.06,334983.28,335390.37
1076,NK17LGF,05/01/2021,2021-01-05 04:22:00,2021-01-05 16:54:00,06:12:12,25.85,00:00:00,0.00,06:20:05,26.39,11:27:43,47.76,12:32:17,52.24,26,204.12,328.50,26.36,119.83,7.74,36.48,335390.37,335718.87
1077,NK17LGF,06/01/2021,2021-01-06 06:07:00,2021-01-06 16:44:00,03:30:34,14.62,00:00:00,0.00,07:06:44,29.63,13:22:42,55.74,10:37:18,44.26,33,79.54,128.01,7.96,36.18,10.00,28.26,335718.87,335846.88
1078,NK17LGF,07/01/2021,2021-01-07 04:35:00,2021-01-07 14:37:00,05:18:42,22.13,00:00:00,0.00,04:43:02,19.66,13:58:16,58.21,10:01:44,41.79,44,143.58,231.08,16.27,73.97,8.82,32.01,335846.88,336077.95
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1364,NK17LGF,22/12/2021,2021-12-22 04:34:00,2021-12-23 00:00:00,08:43:37,36.36,00:04:08,0.29,10:37:21,44.26,04:34:54,19.09,19:25:06,80.91,29,393.00,632.47,41.34,187.94,9.51,29.71,457032.65,457665.12
1365,NK17LGF,23/12/2021,2021-12-23 00:00:00,2021-12-23 23:50:00,07:35:10,31.61,00:00:00,0.00,16:15:39,67.75,00:09:11,0.64,23:50:49,99.36,36,256.94,413.51,36.54,166.11,7.03,40.17,457665.12,458078.63
1366,NK17LGF,24/12/2021,2021-12-24 00:36:00,2021-12-24 07:51:00,02:56:46,12.28,00:00:00,0.00,04:18:02,17.92,16:45:12,69.81,07:14:48,30.19,9,103.14,165.99,11.47,52.14,8.99,31.41,458078.63,458244.61
1367,NK17LGF,29/12/2021,2021-12-29 15:30:00,2021-12-29 15:34:00,00:00:00,0.00,00:00:00,0.00,00:03:26,0.24,23:56:34,99.76,00:03:26,0.24,0,0.00,0.00,0.10,0.43,0.00,0.00,458244.61,458244.61
1368,NK17LGF,31/12/2021,2021-12-31 09:40:00,2021-12-31 11:41:00,01:00:10,4.18,00:00:00,0.00,01:00:35,4.21,21:59:15,91.61,02:00:45,8.39,7,26.46,42.58,3.62,16.45,7.31,38.63,458244.61,458287.19

In [28]:
dfTry["DATE"] = pd.to_datetime(dfTry["DATE"])
dfTry["START"] = pd.to_datetime(dfTry["START"])
dfTry["END"] = pd.to_datetime(dfTry["END"])

C:\Users\saqui\AppData\Local\Temp/ipykernel_10448/2634539196.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfTry["DATE"] = pd.to_datetime(dfTry["DATE"])
C:\Users\saqui\AppData\Local\Temp/ipykernel_10448/2634539196.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfTry["START"] = pd.to_datetime(dfTry["START"])
C:\Users\saqui\AppData\Local\Temp/ipykernel_10448/2634539196.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfTry["END"] = pd.to_datetime(dfTry["END"])

In [29]:
dfTry.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 295 entries, 1076 to 1370
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   REG               295 non-null    object
 1   DATE              295 non-null    datetime64[ns]
 2   START             295 non-null    datetime64[ns]
 3   END               295 non-null    datetime64[ns]
 4   DRIVING_TIME      295 non-null    object
 5   DRIVE_PERC        295 non-null    float64
 6   IDLE_TIME         295 non-null    object
 7   IDLE_PERC         295 non-null    float64
 8   STANDING_TIME     295 non-null    object
 9   STANDING_PERC     295 non-null    float64
 10  INACTIVE_TIME     295 non-null    object
 11  INACTIVE_PERC     295 non-null    float64
 12  UTILISATION       295 non-null    object
 13  UTILISATION_PERC  295 non-null    float64
 14  JOURNEYS          295 non-null    int64
 15  MILES             295 non-null    float64
 16  KM                295 non-null    float64
 17  GALLONS           295 non-null    float64
 18  LITRES            295 non-null    float64
 19  MPG               295 non-null    float64
 20  L_100KM           295 non-null    float64
 21  ODOMETER_START    295 non-null    float64
 22  ODOMETER_END      295 non-null    float64
dtypes: datetime64[ns](3), float64(13), int64(1), object(6)
memory usage: 55.3+ KB

In [23]:
dfTransportJobs = pd.read_excel("D:/Hackathon2022/Decarbonising_Supply_Chain/Data/2. Transport jobs_2021.xlsx")
dfTransportJobs

,DRIVER,REG,TRL,DATE,JOB REF,CUSTOMER,ORDER No,J TYPE,WEIGHT,CONTAINER REF,TYPE,HAZ,COLLECT FROM,LOAD/DISCHARGE CUSTOMER,LOAD/DISCHARGE,DEL TIME,DELIVER TO
0,Port Driver_28,TUG,POT323XTL,2021-01-02,701954/ 1/D,TATA OUTBOUND,EMPTY PALLETS,CUR,NaN,NaN,NaN,-1,EAGLESCLIFFE,TETLEY,EAGLESCLIFFE,00:00:01,SOUTH SHIELDS
1,Port Driver_20,NK17LGD,POT-20-018,2021-01-02,700993/ 1/D,NISSAN MOTOR MANUFACTURING UK,1-1,IMP,NaN,AXIU1653829,40HC,-1,SOUTH SHIELDS,VANTEC KD IMPORTS,WASHINGTON,08:00:01,SOUTH SHIELDS
2,Port Driver_20,NK17LGD,POT-20-040,2021-01-02,701005/ 1/D,NISSAN MOTOR MANUFACTURING UK,1-3,IMP,NaN,MSKU1951479,40HC,-1,SOUTH SHIELDS,VANTEC KD IMPORTS,WASHINGTON,09:30:01,SOUTH SHIELDS
3,Port Driver_20,NK17LGD,POT323XTL,2021-01-02,700903/ 1/D,PORT OF TYNE AUTHORITY,STANDBY,CUR,NaN,NaN,NaN,-1,WALKER,WELLSTREAM / GE OIL & GAS,WALKER,10:30:01,SOUTH SHIELDS
4,Port Driver_20,NK17LGD,POT-20-011,2021-01-02,701945/ 1/D,OCEAN NETWORK EXPRESS PTE LTD,LIVA69945700,EXP,NaN,NYKU4332424,40HC,-1,SOUTH SHIELDS,ALDI DARLINGTON,DARLINGTON,11:00:00,SOUTH SHIELDS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20721,Agency driver_6,NK67LLC,POT-20-010,2021-12-31,725871/ 1/D,VIPA LAUSANNE SA,215325771,EXP,NaN,TGBU5356535,40HC,-1,SOUTH SHIELDS,HW MARTIN (PREMIER WASTE),WASHINGTON,10:00:01,SOUTH SHIELDS
20722,Subcontractor_12,V009,NaN,2021-12-31,725872/ 1/D,MAERSK A/S,213972944,IMP,NaN,MSKU7976411,20GP,-1,SOUTH SHIELDS,NIPPON EXPRESS WAREHOUSE,BOLDON,10:00:01,SOUTH SHIELDS
20723,Port Driver_33,NK67LLA,NaN,2021-12-31,725874/ 1/D,VIPA LAUSANNE SA,215296679,EXP,NaN,MSKU8618412,40HC,-1,SOUTH SHIELDS,J&B RECYCLING,HARTLEPOOL,10:00:01,SOUTH SHIELDS
20724,Subcontractor_7,K012,NaN,2021-12-31,725867/ 1/D,KUEHNE + NAGEL LTD,1042081017-1872,IMP,NaN,UACU5254495,40HC,-1,SOUTH SHIELDS,LANCHESTER WINES,FELLING,11:00:01,SOUTH SHIELDS
20725,Port Driver_12,NK17LGG,POT328XTL,2021-12-31,725946/ 1/D,Baker Hughes Energy Technology,POT03122021-3,CUR,NaN,NaN,NaN,-1,SOUTH SHIELDS,WELLSTREAM / GE OIL & GAS,WALKER,12:00:01,SOUTH SHIELDS

In [25]:
dfTransportJobs["WEIGHT"].mean()

nan

In [21]:
dfTransportJobs["REG"].unique()

array(['TUG', 'NK17LGD', 'NK17LGE', 'NK17LGF', 'NK67LKY', 'NK17LGJ',
       'NK17LGL', 'NK67LLA', 'NK67LKF', 'NK67LKE', 'NK67LKD', 'NK67LKX',
       'E012', 'NK17LGG', 'NK67LKZ', 'KP63HZR', 'S043', 'NK67LLC', 'O010',
       'DX660YU', 'G011', 'DX66PFJ', 'G012', 'KNO01', 'F002', 'V009',
       'DG67EGZ', nan, 'S035', 'P024', 'YM17NCA', 'K012', 'T032', 'KCL01'],
      dtype=object)

In [30]:
dfTryJob = dfTransportJobs[dfTransportJobs["REG"] == "NK17LGF"]
dfTryJob

,DRIVER,REG,TRL,DATE,JOB REF,CUSTOMER,ORDER No,J TYPE,WEIGHT,CONTAINER REF,TYPE,HAZ,COLLECT FROM,LOAD/DISCHARGE CUSTOMER,LOAD/DISCHARGE,DEL TIME,DELIVER TO
13,Port Driver_10,NK17LGF,POT328XTL,2021-01-04,701347/ 1/D,TATA OUTBOUND,POTL25226,CUR,NaN,NaN,NaN,-1,SOUTH SHIELDS,TETLEY,EAGLESCLIFFE,05:30:01,SOUTH SHIELDS
14,Port Driver_10,NK17LGF,POT328XTL,2021-01-04,701367/ 1/D,TATA INBOUND FINISHED,STOCK TRANSFER,CUR,NaN,NaN,NaN,-1,EAGLESCLIFFE,TETLEY,EAGLESCLIFFE,05:31:01,SOUTH SHIELDS
30,Port Driver_10,NK17LGF,POT329XTL,2021-01-04,701357/ 1/D,TATA OUTBOUND,POTL25228,CUR,NaN,NaN,NaN,-1,SOUTH SHIELDS,TETLEY,EAGLESCLIFFE,09:15:01,SOUTH SHIELDS
31,Port Driver_10,NK17LGF,POT329XTL,2021-01-04,701972/ 1/D,TATA INBOUND FINISHED,STOCK TRANSFER,CUR,NaN,NaN,NaN,-1,EAGLESCLIFFE,TETLEY,EAGLESCLIFFE,09:16:01,SOUTH SHIELDS
46,Port Driver_10,NK17LGF,POT318XTL,2021-01-04,701362/ 1/D,TATA OUTBOUND,POTL25229,CUR,NaN,NaN,NaN,-1,SOUTH SHIELDS,TETLEY,EAGLESCLIFFE,14:00:01,SOUTH SHIELDS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20512,Port Driver_18,NK17LGF,POT318XTL,2021-12-23,724886/ 1/D,TATA OUTBOUND,POTL26378,CUR,NaN,NaN,NaN,-1,SOUTH SHIELDS,TETLEY,EAGLESCLIFFE,09:15:01,SOUTH SHIELDS
20545,Port Driver_33,NK17LGF,POT-20-011,2021-12-23,725680/ 1/D,KUEHNE + NAGEL LTD,1042284795-1872,IMP,NaN,XINU1149535,20GP,-1,SOUTH SHIELDS,GREENCROFT BOTTLING,UNIT6 THE GROVE IND EST CONSET,20:00:01,SOUTH SHIELDS
20547,Port Driver_33,NK17LGF,POT-20-011,2021-12-24,725743/ 1/D,HILLEBRAND BULK LOGISTICS,CLS-GBT-2111-0036,IMP,NaN,TRHU2475998,20GP,-1,SOUTH SHIELDS,GREENCROFT BOTTLING,STANLEY,01:00:01,SOUTH SHIELDS
20551,Port Driver_18,NK17LGF,POT330XTL,2021-12-24,724851/ 1/D,TATA OUTBOUND,POTL26380K,CUR,NaN,NaN,NaN,-1,SOUTH SHIELDS,TETLEY,EAGLESCLIFFE,05:30:01,SOUTH SHIELDS
20552,Port Driver_18,NK17LGF,POT330XTL,2021-12-24,724867/ 1/D,TATA OUTBOUND,EMPTY PALLETS,CUR,NaN,NaN,NaN,-1,EAGLESCLIFFE,TETLEY,EAGLESCLIFFE,05:31:01,SOUTH SHIELDS

In [31]:
dfTryJob["DATE"] = pd.to_datetime(dfTryJob["DATE"])
dfTryJob

C:\Users\saqui\AppData\Local\Temp/ipykernel_10448/57592874.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfTryJob["DATE"] = pd.to_datetime(dfTryJob["DATE"])

,DRIVER,REG,TRL,DATE,JOB REF,CUSTOMER,ORDER No,J TYPE,WEIGHT,CONTAINER REF,TYPE,HAZ,COLLECT FROM,LOAD/DISCHARGE CUSTOMER,LOAD/DISCHARGE,DEL TIME,DELIVER TO
13,Port Driver_10,NK17LGF,POT328XTL,2021-01-04,701347/ 1/D,TATA OUTBOUND,POTL25226,CUR,NaN,NaN,NaN,-1,SOUTH SHIELDS,TETLEY,EAGLESCLIFFE,05:30:01,SOUTH SHIELDS
14,Port Driver_10,NK17LGF,POT328XTL,2021-01-04,701367/ 1/D,TATA INBOUND FINISHED,STOCK TRANSFER,CUR,NaN,NaN,NaN,-1,EAGLESCLIFFE,TETLEY,EAGLESCLIFFE,05:31:01,SOUTH SHIELDS
30,Port Driver_10,NK17LGF,POT329XTL,2021-01-04,701357/ 1/D,TATA OUTBOUND,POTL25228,CUR,NaN,NaN,NaN,-1,SOUTH SHIELDS,TETLEY,EAGLESCLIFFE,09:15:01,SOUTH SHIELDS
31,Port Driver_10,NK17LGF,POT329XTL,2021-01-04,701972/ 1/D,TATA INBOUND FINISHED,STOCK TRANSFER,CUR,NaN,NaN,NaN,-1,EAGLESCLIFFE,TETLEY,EAGLESCLIFFE,09:16:01,SOUTH SHIELDS
46,Port Driver_10,NK17LGF,POT318XTL,2021-01-04,701362/ 1/D,TATA OUTBOUND,POTL25229,CUR,NaN,NaN,NaN,-1,SOUTH SHIELDS,TETLEY,EAGLESCLIFFE,14:00:01,SOUTH SHIELDS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20512,Port Driver_18,NK17LGF,POT318XTL,2021-12-23,724886/ 1/D,TATA OUTBOUND,POTL26378,CUR,NaN,NaN,NaN,-1,SOUTH SHIELDS,TETLEY,EAGLESCLIFFE,09:15:01,SOUTH SHIELDS
20545,Port Driver_33,NK17LGF,POT-20-011,2021-12-23,725680/ 1/D,KUEHNE + NAGEL LTD,1042284795-1872,IMP,NaN,XINU1149535,20GP,-1,SOUTH SHIELDS,GREENCROFT BOTTLING,UNIT6 THE GROVE IND EST CONSET,20:00:01,SOUTH SHIELDS
20547,Port Driver_33,NK17LGF,POT-20-011,2021-12-24,725743/ 1/D,HILLEBRAND BULK LOGISTICS,CLS-GBT-2111-0036,IMP,NaN,TRHU2475998,20GP,-1,SOUTH SHIELDS,GREENCROFT BOTTLING,STANLEY,01:00:01,SOUTH SHIELDS
20551,Port Driver_18,NK17LGF,POT330XTL,2021-12-24,724851/ 1/D,TATA OUTBOUND,POTL26380K,CUR,NaN,NaN,NaN,-1,SOUTH SHIELDS,TETLEY,EAGLESCLIFFE,05:30:01,SOUTH SHIELDS
20552,Port Driver_18,NK17LGF,POT330XTL,2021-12-24,724867/ 1/D,TATA OUTBOUND,EMPTY PALLETS,CUR,NaN,NaN,NaN,-1,EAGLESCLIFFE,TETLEY,EAGLESCLIFFE,05:31:01,SOUTH SHIELDS

In [32]:
def merge_clean(df1, df2, key):
    
    df_merged = pd.merge(df1, df2, how="inner", on = key)
    
    for col in df_merged.columns:
        if col.endswith("_x"):
            df_merged.rename(columns = lambda col:col.rstrip("_x"), inplace = True)
        elif col.endswith("_y"):
            to_drop = [col for col in df_merged if col.endswith("_y")]
            df_merged.drop(to_drop, axis = 1, inplace = True)
        else:
            pass
    return df_merged

In [33]:
df_final = merge_clean(dfTry, dfTryJob, "DATE")
df_final.head()

,REG,DATE,START,END,DRIVING_TIME,DRIVE_PERC,IDLE_TIME,IDLE_PERC,STANDING_TIME,STANDING_PERC,INACTIVE_TIME,INACTIVE_PERC,UTILISATION,UTILISATION_PERC,JOURNEYS,MILES,KM,GALLONS,LITRES,MPG,L_100KM,ODOMETER_START,ODOMETER_END,DRIVER,TRL,JOB REF,CUSTOMER,ORDER No,J TYPE,WEIGHT,CONTAINER REF,TYPE,HAZ,COLLECT FROM,LOAD/DISCHARGE CUSTOMER,LOAD/DISCHARGE,DEL TIME,DELIVER TO
0,NK17LGF,2021-03-01,2021-01-03 11:19:00,2021-01-03 11:31:00,00:05:18,0.37,00:00:00,0.0,00:06:23,0.44,23:48:19,99.19,00:11:41,0.81,1,0.17,0.28,0.2,0.92,0.84,334.55,334983.01,334983.28,Port Driver_10,POT-20-014,703799/ 1/D,NISSAN MOTOR MANUFACTURING UK,1-1,IMP,NaN,TLLU4199387,40HC,-1,SOUTH SHIELDS,VANTEC KD IMPORTS,WASHINGTON,07:00:01,SOUTH SHIELDS
1,NK17LGF,2021-03-01,2021-01-03 11:19:00,2021-01-03 11:31:00,00:05:18,0.37,00:00:00,0.0,00:06:23,0.44,23:48:19,99.19,00:11:41,0.81,1,0.17,0.28,0.2,0.92,0.84,334.55,334983.01,334983.28,Port Driver_10,POT-20-009,703840/ 1/D,NISSAN MOTOR MANUFACTURING UK,1-2,IMP,NaN,MRKU5606191,40HC,-1,SOUTH SHIELDS,VANTEC KD IMPORTS,WASHINGTON,07:30:01,SOUTH SHIELDS
2,NK17LGF,2021-03-01,2021-01-03 11:19:00,2021-01-03 11:31:00,00:05:18,0.37,00:00:00,0.0,00:06:23,0.44,23:48:19,99.19,00:11:41,0.81,1,0.17,0.28,0.2,0.92,0.84,334.55,334983.01,334983.28,Port Driver_10,POT-20-014,705152/ 1/D,KOMATSU UK LTD (CON),UCR210112,IMP,NaN,MSKU7475786,20GP,-1,SOUTH SHIELDS,KATMEX,SEAHAM,10:00:01,SOUTH SHIELDS
3,NK17LGF,2021-03-01,2021-01-03 11:19:00,2021-01-03 11:31:00,00:05:18,0.37,00:00:00,0.0,00:06:23,0.44,23:48:19,99.19,00:11:41,0.81,1,0.17,0.28,0.2,0.92,0.84,334.55,334983.01,334983.28,Port Driver_10,POT332XTL,705279/ 1/D,FORMICA LIMITED,FORMICA010321A,CUR,NaN,NaN,NaN,-1,SOUTH SHIELDS,FORMICA GROUP,NORTH SHIELDS,11:00:01,SOUTH SHIELDS
4,NK17LGF,2021-03-01,2021-01-03 11:19:00,2021-01-03 11:31:00,00:05:18,0.37,00:00:00,0.0,00:06:23,0.44,23:48:19,99.19,00:11:41,0.81,1,0.17,0.28,0.2,0.92,0.84,334.55,334983.01,334983.28,Port Driver_10,POT-20-014,705155/ 1/D,ALBATRANS LONDON (UK) LTD,M92764,IMP,NaN,TGBU3179997,20GP,-1,SOUTH SHIELDS,GREENCROFT BOTTLING,STANLEY,15:00:01,SOUTH SHIELDS