In [91]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 

import seaborn as sns

In [92]:
pd.set_option('max_columns', None)

In [93]:
df = pd.read_csv("../../HackathonNICD/Data/1. Mandata Vehicle Summary.csv")
df

,REG,DATE,START,END,DRIVING_TIME,DRIVE_PERC,IDLE_TIME,IDLE_PERC,STANDING_TIME,STANDING_PERC,INACTIVE_TIME,INACTIVE_PERC,UTILISATION,UTILISATION_PERC,JOURNEYS,MILES,KM,GALLONS,LITRES,MPG,L_100KM,ODOMETER_START,ODOMETER_END
0,DX66OYU,26/05/2021,2021-05-26 12:33:00,2021-05-27 01:00:00,05:57:59,24.86,00:00:16,0.02,06:28:29,26.98,11:33:16,48.14,12:26:44,51.86,59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,593088.25
1,DX66OYU,27/05/2021,2021-05-27 01:00:00,2021-05-27 18:09:00,06:26:42,26.85,00:01:18,0.09,10:41:05,44.52,06:50:55,28.54,17:09:05,71.46,43,164.16,264.19,18.95,86.13,8.66,32.60,593088.25,593352.44
2,DX66OYU,28/05/2021,2021-05-28 06:54:00,2021-05-28 20:19:00,08:38:19,35.99,00:00:02,0.00,04:45:55,19.86,10:35:44,44.15,13:24:16,55.85,19,316.42,509.23,37.45,170.24,8.45,33.43,593352.44,593861.67
3,DX66OYU,01/06/2021,2021-06-01 06:54:00,2021-06-02 00:46:00,08:29:09,35.36,00:00:57,0.07,09:21:41,39.01,06:08:13,25.57,17:51:47,74.43,48,282.48,454.61,31.39,142.72,9.00,31.39,593861.67,594316.27
4,DX66OYU,02/06/2021,2021-06-02 06:25:00,2021-06-02 18:24:00,04:34:05,19.03,00:00:00,0.00,07:24:37,30.88,12:01:18,50.09,11:58:42,49.91,35,84.36,135.77,12.99,59.07,6.49,43.51,594316.27,594452.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4494,YM17NCA,22/12/2021,2021-12-22 07:00:00,2021-12-23 00:00:00,03:59:07,16.61,00:12:24,0.86,12:47:56,53.33,07:00:33,29.20,16:59:27,70.80,23,78.66,126.59,15.65,71.15,5.03,56.20,477036.90,477163.49
4495,YM17NCA,23/12/2021,2021-12-23 00:00:00,2021-12-23 15:05:00,04:51:23,20.23,00:00:00,0.00,10:14:34,42.68,08:54:03,37.09,15:05:57,62.91,30,101.85,163.91,13.96,63.47,7.30,38.72,477163.49,477327.39
4496,YM17NCA,24/12/2021,2021-12-24 11:22:00,2021-12-24 11:24:00,00:01:02,0.07,00:00:00,0.00,00:01:10,0.08,23:57:48,99.85,00:02:12,0.15,1,0.05,0.09,0.03,0.15,1.64,172.94,477327.39,477327.48
4497,YM17NCA,30/12/2021,2021-12-30 13:10:00,2021-12-30 14:20:00,00:00:00,0.00,00:36:23,2.53,00:34:05,2.37,22:49:32,95.11,01:10:28,4.89,0,0.00,0.00,0.42,1.92,0.00,0.00,477327.48,477327.48
4498,YM17NCA,31/12/2021,2021-12-31 08:42:00,2021-12-31 12:06:00,00:27:24,1.90,00:36:05,2.51,02:20:38,9.77,20:35:53,85.83,03:24:07,14.17,10,2.44,3.92,0.85,3.88,2.85,99.03,477327.48,477331.40

In [94]:
df = df.dropna()
df = df.reset_index(drop = True)
df

,REG,DATE,START,END,DRIVING_TIME,DRIVE_PERC,IDLE_TIME,IDLE_PERC,STANDING_TIME,STANDING_PERC,INACTIVE_TIME,INACTIVE_PERC,UTILISATION,UTILISATION_PERC,JOURNEYS,MILES,KM,GALLONS,LITRES,MPG,L_100KM,ODOMETER_START,ODOMETER_END
0,DX66OYU,27/05/2021,2021-05-27 01:00:00,2021-05-27 18:09:00,06:26:42,26.85,00:01:18,0.09,10:41:05,44.52,06:50:55,28.54,17:09:05,71.46,43,164.16,264.19,18.95,86.13,8.66,32.60,593088.25,593352.44
1,DX66OYU,28/05/2021,2021-05-28 06:54:00,2021-05-28 20:19:00,08:38:19,35.99,00:00:02,0.00,04:45:55,19.86,10:35:44,44.15,13:24:16,55.85,19,316.42,509.23,37.45,170.24,8.45,33.43,593352.44,593861.67
2,DX66OYU,01/06/2021,2021-06-01 06:54:00,2021-06-02 00:46:00,08:29:09,35.36,00:00:57,0.07,09:21:41,39.01,06:08:13,25.57,17:51:47,74.43,48,282.48,454.61,31.39,142.72,9.00,31.39,593861.67,594316.27
3,DX66OYU,02/06/2021,2021-06-02 06:25:00,2021-06-02 18:24:00,04:34:05,19.03,00:00:00,0.00,07:24:37,30.88,12:01:18,50.09,11:58:42,49.91,35,84.36,135.77,12.99,59.07,6.49,43.51,594316.27,594452.04
4,DX66OYU,03/06/2021,2021-06-03 07:56:00,2021-06-04 01:00:00,07:59:22,33.29,00:03:13,0.22,09:01:17,37.59,06:56:08,28.90,17:03:52,71.10,34,273.51,440.18,32.25,146.61,8.48,33.31,594452.04,594892.21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4491,YM17NCA,22/12/2021,2021-12-22 07:00:00,2021-12-23 00:00:00,03:59:07,16.61,00:12:24,0.86,12:47:56,53.33,07:00:33,29.20,16:59:27,70.80,23,78.66,126.59,15.65,71.15,5.03,56.20,477036.90,477163.49
4492,YM17NCA,23/12/2021,2021-12-23 00:00:00,2021-12-23 15:05:00,04:51:23,20.23,00:00:00,0.00,10:14:34,42.68,08:54:03,37.09,15:05:57,62.91,30,101.85,163.91,13.96,63.47,7.30,38.72,477163.49,477327.39
4493,YM17NCA,24/12/2021,2021-12-24 11:22:00,2021-12-24 11:24:00,00:01:02,0.07,00:00:00,0.00,00:01:10,0.08,23:57:48,99.85,00:02:12,0.15,1,0.05,0.09,0.03,0.15,1.64,172.94,477327.39,477327.48
4494,YM17NCA,30/12/2021,2021-12-30 13:10:00,2021-12-30 14:20:00,00:00:00,0.00,00:36:23,2.53,00:34:05,2.37,22:49:32,95.11,01:10:28,4.89,0,0.00,0.00,0.42,1.92,0.00,0.00,477327.48,477327.48
4495,YM17NCA,31/12/2021,2021-12-31 08:42:00,2021-12-31 12:06:00,00:27:24,1.90,00:36:05,2.51,02:20:38,9.77,20:35:53,85.83,03:24:07,14.17,10,2.44,3.92,0.85,3.88,2.85,99.03,477327.48,477331.40

In [62]:
def duration_minutes(df): 
    df["UTILISATION"] = df["UTILISATION"].str.split(":").apply(lambda x: int(x[0]) * 60 + int(x[1]))

    return df

In [63]:
duration_minutes(df)

,REG,DATE,START,END,DRIVING_TIME,DRIVE_PERC,IDLE_TIME,IDLE_PERC,STANDING_TIME,STANDING_PERC,INACTIVE_TIME,INACTIVE_PERC,UTILISATION,UTILISATION_PERC,JOURNEYS,MILES,KM,GALLONS,LITRES,MPG,L_100KM,ODOMETER_START,ODOMETER_END
0,DX66OYU,27/05/2021,2021-05-27 01:00:00,2021-05-27 18:09:00,06:26:42,26.85,00:01:18,0.09,10:41:05,44.52,06:50:55,28.54,1029,71.46,43,164.16,264.19,18.95,86.13,8.66,32.60,593088.25,593352.44
1,DX66OYU,28/05/2021,2021-05-28 06:54:00,2021-05-28 20:19:00,08:38:19,35.99,00:00:02,0.00,04:45:55,19.86,10:35:44,44.15,804,55.85,19,316.42,509.23,37.45,170.24,8.45,33.43,593352.44,593861.67
2,DX66OYU,01/06/2021,2021-06-01 06:54:00,2021-06-02 00:46:00,08:29:09,35.36,00:00:57,0.07,09:21:41,39.01,06:08:13,25.57,1071,74.43,48,282.48,454.61,31.39,142.72,9.00,31.39,593861.67,594316.27
3,DX66OYU,02/06/2021,2021-06-02 06:25:00,2021-06-02 18:24:00,04:34:05,19.03,00:00:00,0.00,07:24:37,30.88,12:01:18,50.09,718,49.91,35,84.36,135.77,12.99,59.07,6.49,43.51,594316.27,594452.04
4,DX66OYU,03/06/2021,2021-06-03 07:56:00,2021-06-04 01:00:00,07:59:22,33.29,00:03:13,0.22,09:01:17,37.59,06:56:08,28.90,1023,71.10,34,273.51,440.18,32.25,146.61,8.48,33.31,594452.04,594892.21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4491,YM17NCA,22/12/2021,2021-12-22 07:00:00,2021-12-23 00:00:00,03:59:07,16.61,00:12:24,0.86,12:47:56,53.33,07:00:33,29.20,1019,70.80,23,78.66,126.59,15.65,71.15,5.03,56.20,477036.90,477163.49
4492,YM17NCA,23/12/2021,2021-12-23 00:00:00,2021-12-23 15:05:00,04:51:23,20.23,00:00:00,0.00,10:14:34,42.68,08:54:03,37.09,905,62.91,30,101.85,163.91,13.96,63.47,7.30,38.72,477163.49,477327.39
4493,YM17NCA,24/12/2021,2021-12-24 11:22:00,2021-12-24 11:24:00,00:01:02,0.07,00:00:00,0.00,00:01:10,0.08,23:57:48,99.85,2,0.15,1,0.05,0.09,0.03,0.15,1.64,172.94,477327.39,477327.48
4494,YM17NCA,30/12/2021,2021-12-30 13:10:00,2021-12-30 14:20:00,00:00:00,0.00,00:36:23,2.53,00:34:05,2.37,22:49:32,95.11,70,4.89,0,0.00,0.00,0.42,1.92,0.00,0.00,477327.48,477327.48
4495,YM17NCA,31/12/2021,2021-12-31 08:42:00,2021-12-31 12:06:00,00:27:24,1.90,00:36:05,2.51,02:20:38,9.77,20:35:53,85.83,204,14.17,10,2.44,3.92,0.85,3.88,2.85,99.03,477327.48,477331.40

In [64]:
df["mileage"] = df["MPG"] * 0.43 
df

,REG,DATE,START,END,DRIVING_TIME,DRIVE_PERC,IDLE_TIME,IDLE_PERC,STANDING_TIME,STANDING_PERC,INACTIVE_TIME,INACTIVE_PERC,UTILISATION,UTILISATION_PERC,JOURNEYS,MILES,KM,GALLONS,LITRES,MPG,L_100KM,ODOMETER_START,ODOMETER_END,mileage
0,DX66OYU,27/05/2021,2021-05-27 01:00:00,2021-05-27 18:09:00,06:26:42,26.85,00:01:18,0.09,10:41:05,44.52,06:50:55,28.54,1029,71.46,43,164.16,264.19,18.95,86.13,8.66,32.60,593088.25,593352.44,3.7238
1,DX66OYU,28/05/2021,2021-05-28 06:54:00,2021-05-28 20:19:00,08:38:19,35.99,00:00:02,0.00,04:45:55,19.86,10:35:44,44.15,804,55.85,19,316.42,509.23,37.45,170.24,8.45,33.43,593352.44,593861.67,3.6335
2,DX66OYU,01/06/2021,2021-06-01 06:54:00,2021-06-02 00:46:00,08:29:09,35.36,00:00:57,0.07,09:21:41,39.01,06:08:13,25.57,1071,74.43,48,282.48,454.61,31.39,142.72,9.00,31.39,593861.67,594316.27,3.8700
3,DX66OYU,02/06/2021,2021-06-02 06:25:00,2021-06-02 18:24:00,04:34:05,19.03,00:00:00,0.00,07:24:37,30.88,12:01:18,50.09,718,49.91,35,84.36,135.77,12.99,59.07,6.49,43.51,594316.27,594452.04,2.7907
4,DX66OYU,03/06/2021,2021-06-03 07:56:00,2021-06-04 01:00:00,07:59:22,33.29,00:03:13,0.22,09:01:17,37.59,06:56:08,28.90,1023,71.10,34,273.51,440.18,32.25,146.61,8.48,33.31,594452.04,594892.21,3.6464
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4491,YM17NCA,22/12/2021,2021-12-22 07:00:00,2021-12-23 00:00:00,03:59:07,16.61,00:12:24,0.86,12:47:56,53.33,07:00:33,29.20,1019,70.80,23,78.66,126.59,15.65,71.15,5.03,56.20,477036.90,477163.49,2.1629
4492,YM17NCA,23/12/2021,2021-12-23 00:00:00,2021-12-23 15:05:00,04:51:23,20.23,00:00:00,0.00,10:14:34,42.68,08:54:03,37.09,905,62.91,30,101.85,163.91,13.96,63.47,7.30,38.72,477163.49,477327.39,3.1390
4493,YM17NCA,24/12/2021,2021-12-24 11:22:00,2021-12-24 11:24:00,00:01:02,0.07,00:00:00,0.00,00:01:10,0.08,23:57:48,99.85,2,0.15,1,0.05,0.09,0.03,0.15,1.64,172.94,477327.39,477327.48,0.7052
4494,YM17NCA,30/12/2021,2021-12-30 13:10:00,2021-12-30 14:20:00,00:00:00,0.00,00:36:23,2.53,00:34:05,2.37,22:49:32,95.11,70,4.89,0,0.00,0.00,0.42,1.92,0.00,0.00,477327.48,477327.48,0.0000
4495,YM17NCA,31/12/2021,2021-12-31 08:42:00,2021-12-31 12:06:00,00:27:24,1.90,00:36:05,2.51,02:20:38,9.77,20:35:53,85.83,204,14.17,10,2.44,3.92,0.85,3.88,2.85,99.03,477327.48,477331.40,1.2255

In [65]:
df.drop(["ODOMETER_START", "ODOMETER_END", "JOURNEYS", "GALLONS", "MPG", "MILES"], axis = 1, inplace = True, errors="ignore")

In [66]:
df

,REG,DATE,START,END,DRIVING_TIME,DRIVE_PERC,IDLE_TIME,IDLE_PERC,STANDING_TIME,STANDING_PERC,INACTIVE_TIME,INACTIVE_PERC,UTILISATION,UTILISATION_PERC,KM,LITRES,L_100KM,mileage
0,DX66OYU,27/05/2021,2021-05-27 01:00:00,2021-05-27 18:09:00,06:26:42,26.85,00:01:18,0.09,10:41:05,44.52,06:50:55,28.54,1029,71.46,264.19,86.13,32.60,3.7238
1,DX66OYU,28/05/2021,2021-05-28 06:54:00,2021-05-28 20:19:00,08:38:19,35.99,00:00:02,0.00,04:45:55,19.86,10:35:44,44.15,804,55.85,509.23,170.24,33.43,3.6335
2,DX66OYU,01/06/2021,2021-06-01 06:54:00,2021-06-02 00:46:00,08:29:09,35.36,00:00:57,0.07,09:21:41,39.01,06:08:13,25.57,1071,74.43,454.61,142.72,31.39,3.8700
3,DX66OYU,02/06/2021,2021-06-02 06:25:00,2021-06-02 18:24:00,04:34:05,19.03,00:00:00,0.00,07:24:37,30.88,12:01:18,50.09,718,49.91,135.77,59.07,43.51,2.7907
4,DX66OYU,03/06/2021,2021-06-03 07:56:00,2021-06-04 01:00:00,07:59:22,33.29,00:03:13,0.22,09:01:17,37.59,06:56:08,28.90,1023,71.10,440.18,146.61,33.31,3.6464
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4491,YM17NCA,22/12/2021,2021-12-22 07:00:00,2021-12-23 00:00:00,03:59:07,16.61,00:12:24,0.86,12:47:56,53.33,07:00:33,29.20,1019,70.80,126.59,71.15,56.20,2.1629
4492,YM17NCA,23/12/2021,2021-12-23 00:00:00,2021-12-23 15:05:00,04:51:23,20.23,00:00:00,0.00,10:14:34,42.68,08:54:03,37.09,905,62.91,163.91,63.47,38.72,3.1390
4493,YM17NCA,24/12/2021,2021-12-24 11:22:00,2021-12-24 11:24:00,00:01:02,0.07,00:00:00,0.00,00:01:10,0.08,23:57:48,99.85,2,0.15,0.09,0.15,172.94,0.7052
4494,YM17NCA,30/12/2021,2021-12-30 13:10:00,2021-12-30 14:20:00,00:00:00,0.00,00:36:23,2.53,00:34:05,2.37,22:49:32,95.11,70,4.89,0.00,1.92,0.00,0.0000
4495,YM17NCA,31/12/2021,2021-12-31 08:42:00,2021-12-31 12:06:00,00:27:24,1.90,00:36:05,2.51,02:20:38,9.77,20:35:53,85.83,204,14.17,3.92,3.88,99.03,1.2255

In [67]:
df = df.sort_values(by=['DATE'])
df = df.reset_index(drop = True)
df

,REG,DATE,START,END,DRIVING_TIME,DRIVE_PERC,IDLE_TIME,IDLE_PERC,STANDING_TIME,STANDING_PERC,INACTIVE_TIME,INACTIVE_PERC,UTILISATION,UTILISATION_PERC,KM,LITRES,L_100KM,mileage
0,NK67LKY,01/02/2021,2021-02-01 04:10:00,2021-02-01 17:18:00,05:35:46,23.32,00:00:00,0.00,07:32:18,31.41,10:51:56,45.27,788,54.73,252.34,105.87,41.96,2.8939
1,NK67LKF,01/02/2021,2021-02-01 05:22:00,2021-02-01 17:25:00,05:03:11,21.05,00:00:00,0.00,07:00:28,29.20,11:56:21,49.75,723,50.25,208.72,70.21,33.64,3.6120
2,NK67LKZ,01/02/2021,2021-02-01 06:05:00,2021-02-01 19:30:00,07:33:36,31.50,00:00:12,0.01,05:50:50,24.36,10:35:22,44.12,804,55.88,423.01,120.62,28.52,4.2613
3,NK67LKX,01/02/2021,2021-02-01 07:14:00,2021-02-02 00:00:00,06:45:06,28.13,00:00:39,0.05,09:59:47,41.65,07:14:28,30.17,1005,69.83,203.43,89.17,43.83,2.7692
4,NK17LGJ,01/02/2021,2021-02-01 06:05:00,2021-02-01 19:16:00,07:37:08,31.75,00:00:00,0.00,05:33:14,23.14,10:49:38,45.11,790,54.89,426.99,104.15,24.39,4.9794
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4491,NK67LKF,31/12/2021,2021-12-31 10:44:00,2021-12-31 10:58:00,00:05:17,0.37,00:07:23,0.51,00:01:13,0.08,23:46:07,99.04,13,0.96,0.35,1.09,315.36,0.3827
4492,NK67LKX,31/12/2021,2021-12-31 03:55:00,2021-12-31 14:16:00,05:46:55,24.09,00:01:42,0.12,04:32:11,18.90,13:39:12,56.89,620,43.11,246.95,84.57,34.25,3.5475
4493,NK67LKY,31/12/2021,2021-12-31 04:35:00,2021-12-31 12:54:00,03:53:17,16.20,00:06:04,0.42,04:20:09,18.07,15:40:30,65.31,499,34.69,264.31,102.08,38.62,3.1433
4494,KP63HZR,31/12/2021,2021-12-31 07:34:00,2021-12-31 10:51:00,00:51:26,3.57,00:00:00,0.00,02:25:07,10.08,20:43:27,86.35,196,13.65,20.62,11.50,55.77,2.1801
4495,YM17NCA,31/12/2021,2021-12-31 08:42:00,2021-12-31 12:06:00,00:27:24,1.90,00:36:05,2.51,02:20:38,9.77,20:35:53,85.83,204,14.17,3.92,3.88,99.03,1.2255

In [81]:
df_annual.head()

,REG,DRIVING_TIME,DRIVING_PERC,IDLE_TIME,IDLE_PERC,STANDING_TIME,STANDING_PERC,INACTIVE_TIME,INACTIVE_PERC,UTILISATION_TIME,UTILISATION_PERC,JOURNEYS,MILES,KM,GALLONS,LITRES,MPG,L_100KM,ODOMETER_START,ODOMETER_END,CO2_LBS,CO2_KG,util_min
0,DX66OYU,1222:41:20,30.51,10:13:33,0.26,1587:20:09,39.60,1187:44:58,29.63,169215,70.37,6311,40179.07,64662.08,4592.16,20876.43,1391.39,7815.94,593088.25,657749.97,121565.294305,55141.09,0.325864
1,DX66PFJ,710:14:58,36.54,02:31:54,0.13,654:45:06,33.68,576:28:02,29.65,82051,70.35,2747,27776.07,44701.41,2904.58,13204.25,728.78,3284.45,450256.78,494957.96,76889.300344,34876.40,0.425058
2,KP63HZR,1911:32:27,29.61,07:00:02,0.11,2468:05:28,38.23,2069:22:03,32.05,263197,67.95,11539,59779.95,96206.93,7183.39,32654.50,2161.55,9818.92,399489.12,495695.40,190149.428500,86250.33,0.327703
3,NK17LGD,1875:24:53,27.51,05:21:16,0.08,1933:03:51,28.36,3002:10:00,44.05,228830,55.95,8470,70040.09,112719.02,7866.50,35761.53,2447.39,10908.87,345915.39,458633.75,208241.928586,94456.95,0.412782
4,NK17LGE,1801:27:33,27.29,05:49:52,0.09,2097:54:17,31.79,2694:48:18,40.83,234311,59.17,9674,61048.30,98248.16,7283.19,33109.87,2172.29,13364.21,351078.90,449326.39,192800.729710,87452.94,0.373234

In [82]:
dfannual_clip = df_annual[["REG","util_min"]]

In [87]:
dfannual_clip

        REG  util_min
0   DX66OYU  0.325864
1   DX66PFJ  0.425058
2   KP63HZR  0.327703
3   NK17LGD  0.412782
4   NK17LGE  0.373234
5   NK17LGF  0.397813
6   NK17LGG  0.352411
7   NK17LGJ  0.328649
8   NK17LGL  0.386274
9   NK67LKD  0.359988
10  NK67LKE  0.349734
11  NK67LKF  0.348080
12  NK67LKX  0.359975
13  NK67LKY  0.377094
14  NK67LKZ  0.336310
15  NK67LLA  0.345432
16  NK67LLC  0.331949
17  YM17NCA  0.313207

In [84]:
newdf = pd.merge(df, dfannual_clip, on="REG", how="outer")

In [85]:
newdf.head()

,REG,DATE,START,END,DRIVING_TIME,DRIVE_PERC,IDLE_TIME,IDLE_PERC,STANDING_TIME,STANDING_PERC,INACTIVE_TIME,INACTIVE_PERC,UTILISATION,UTILISATION_PERC,KM,LITRES,L_100KM,mileage,CO2,util_min
0,NK67LKY,2021-01-02,2021-02-01 04:10:00,2021-02-01 17:18:00,05:35:46,23.32,00:00:00,0.00,07:32:18,31.41,10:51:56,45.27,788,54.73,252.34,105.87,41.96,2.8939,256.780894,0.377094
1,NK67LKY,2021-01-03,2021-03-01 05:40:00,2021-03-01 18:20:00,05:48:27,24.20,00:00:00,0.00,06:50:52,28.53,11:20:41,47.27,759,52.73,288.00,98.83,34.32,3.5389,NaN,0.377094
2,NK67LKY,2021-01-04,2021-04-01 06:04:00,2021-04-01 11:44:00,01:55:17,8.01,00:00:00,0.00,03:44:40,15.60,18:20:03,76.39,339,23.61,33.82,15.72,46.48,2.6144,NaN,0.377094
3,NK67LKY,2021-01-06,2021-06-01 04:35:00,2021-06-01 16:46:00,05:16:54,22.01,00:00:00,0.00,06:53:37,28.72,11:49:29,49.27,730,50.73,284.73,97.33,34.18,3.5518,NaN,0.377094
4,NK67LKY,2021-01-07,2021-07-01 01:05:00,2021-07-01 19:23:00,06:40:20,27.80,00:01:51,0.13,11:36:00,48.33,05:41:49,23.74,1098,76.26,411.44,115.06,27.97,4.3430,NaN,0.377094

In [86]:
newdf["CO2"] = newdf["util_min"] * newdf["UTILISATION"]
newdf

,REG,DATE,START,END,DRIVING_TIME,DRIVE_PERC,IDLE_TIME,IDLE_PERC,STANDING_TIME,STANDING_PERC,INACTIVE_TIME,INACTIVE_PERC,UTILISATION,UTILISATION_PERC,KM,LITRES,L_100KM,mileage,CO2,util_min
0,NK67LKY,2021-01-02,2021-02-01 04:10:00,2021-02-01 17:18:00,05:35:46,23.32,00:00:00,0.00,07:32:18,31.41,10:51:56,45.27,788,54.73,252.34,105.87,41.96,2.8939,297.150076,0.377094
1,NK67LKY,2021-01-03,2021-03-01 05:40:00,2021-03-01 18:20:00,05:48:27,24.20,00:00:00,0.00,06:50:52,28.53,11:20:41,47.27,759,52.73,288.00,98.83,34.32,3.5389,286.214350,0.377094
2,NK67LKY,2021-01-04,2021-04-01 06:04:00,2021-04-01 11:44:00,01:55:17,8.01,00:00:00,0.00,03:44:40,15.60,18:20:03,76.39,339,23.61,33.82,15.72,46.48,2.6144,127.834868,0.377094
3,NK67LKY,2021-01-06,2021-06-01 04:35:00,2021-06-01 16:46:00,05:16:54,22.01,00:00:00,0.00,06:53:37,28.72,11:49:29,49.27,730,50.73,284.73,97.33,34.18,3.5518,275.278624,0.377094
4,NK67LKY,2021-01-07,2021-07-01 01:05:00,2021-07-01 19:23:00,06:40:20,27.80,00:01:51,0.13,11:36:00,48.33,05:41:49,23.74,1098,76.26,411.44,115.06,27.97,4.3430,414.049218,0.377094
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4491,YM17NCA,2021-09-30,2021-09-30 01:00:00,2021-09-30 23:26:00,09:28:17,39.46,00:12:45,0.89,12:45:53,53.19,01:33:05,6.46,1346,93.54,542.53,164.81,30.38,3.9990,421.577191,0.313207
4492,YM17NCA,2021-10-30,2021-10-30 01:00:00,2021-10-30 01:52:00,00:41:15,2.86,00:00:00,0.00,00:11:12,0.78,23:07:33,96.36,52,3.64,43.52,10.93,25.11,4.8375,16.286786,0.313207
4493,YM17NCA,2021-11-30,2021-11-30 00:15:00,2021-12-01 00:00:00,06:40:11,27.79,00:14:46,1.03,16:49:18,70.09,00:15:45,1.09,1424,98.91,239.03,84.90,35.52,3.4185,446.007370,0.313207
4494,YM17NCA,2021-12-30,2021-12-30 13:10:00,2021-12-30 14:20:00,00:00:00,0.00,00:36:23,2.53,00:34:05,2.37,22:49:32,95.11,70,4.89,0.00,1.92,0.00,0.0000,21.924520,0.313207
4495,YM17NCA,2021-12-31,2021-12-31 08:42:00,2021-12-31 12:06:00,00:27:24,1.90,00:36:05,2.51,02:20:38,9.77,20:35:53,85.83,204,14.17,3.92,3.88,99.03,1.2255,63.894314,0.313207

In [90]:
newdf["CO2"].isnull().sum()

0

In [75]:
sum(df["UTILISATION"])

3905076

In [68]:
df["DATE"] = pd.to_datetime(df["DATE"])
df["START"] = pd.to_datetime(df["START"])
df["END"] = pd.to_datetime(df["END"])

In [69]:
df["REG"].unique()

array(['NK67LKY', 'NK67LKF', 'NK67LKZ', 'NK67LKX', 'NK17LGJ', 'NK67LKD',
       'NK67LKE', 'NK17LGF', 'NK17LGL', 'NK17LGD', 'KP63HZR', 'NK17LGG',
       'NK17LGE', 'NK67LLC', 'NK67LLA', 'DX66OYU', 'DX66PFJ', 'YM17NCA'],
      dtype=object)

In [70]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4496 entries, 0 to 4495
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   REG               4496 non-null   object
 1   DATE              4496 non-null   datetime64[ns]
 2   START             4496 non-null   datetime64[ns]
 3   END               4496 non-null   datetime64[ns]
 4   DRIVING_TIME      4496 non-null   object
 5   DRIVE_PERC        4496 non-null   float64
 6   IDLE_TIME         4496 non-null   object
 7   IDLE_PERC         4496 non-null   float64
 8   STANDING_TIME     4496 non-null   object
 9   STANDING_PERC     4496 non-null   float64
 10  INACTIVE_TIME     4496 non-null   object
 11  INACTIVE_PERC     4496 non-null   float64
 12  UTILISATION       4496 non-null   int64
 13  UTILISATION_PERC  4496 non-null   float64
 14  KM                4496 non-null   float64
 15  LITRES            4496 non-null   float64
 16  L_100KM           4496 non-null   float64
 17  mileage           4496 non-null   float64
dtypes: datetime64[ns](3), float64(9), int64(1), object(5)
memory usage: 632.4+ KB

In [71]:
df.DATE.min(), df.DATE.max()

(Timestamp('2021-01-02 00:00:00'), Timestamp('2021-12-31 00:00:00'))

In [72]:
df_annual = pd.read_csv("../../HackathonNICD/Data/1a. Mandata Vehicle Annual Summary.csv")
df_annual

,REG,DRIVING_TIME,DRIVING_PERC,IDLE_TIME,IDLE_PERC,STANDING_TIME,STANDING_PERC,INACTIVE_TIME,INACTIVE_PERC,UTILISATION_TIME,UTILISATION_PERC,JOURNEYS,MILES,KM,GALLONS,LITRES,MPG,L_100KM,ODOMETER_START,ODOMETER_END,CO2_LBS,CO2_KG
0,DX66OYU,1222:41:20,30.51,10:13:33,0.26,1587:20:09,39.60,1187:44:58,29.63,2820:15:02,70.37,6311,40179.07,64662.08,4592.16,20876.43,1391.39,7815.94,593088.25,657749.97,121565.294305,55141.09
1,DX66PFJ,710:14:58,36.54,02:31:54,0.13,654:45:06,33.68,576:28:02,29.65,1367:31:58,70.35,2747,27776.07,44701.41,2904.58,13204.25,728.78,3284.45,450256.78,494957.96,76889.300344,34876.40
2,KP63HZR,1911:32:27,29.61,07:00:02,0.11,2468:05:28,38.23,2069:22:03,32.05,4386:37:57,67.95,11539,59779.95,96206.93,7183.39,32654.50,2161.55,9818.92,399489.12,495695.40,190149.428500,86250.33
3,NK17LGD,1875:24:53,27.51,05:21:16,0.08,1933:03:51,28.36,3002:10:00,44.05,3813:50:00,55.95,8470,70040.09,112719.02,7866.50,35761.53,2447.39,10908.87,345915.39,458633.75,208241.928586,94456.95
4,NK17LGE,1801:27:33,27.29,05:49:52,0.09,2097:54:17,31.79,2694:48:18,40.83,3905:11:42,59.17,9674,61048.30,98248.16,7283.19,33109.87,2172.29,13364.21,351078.90,449326.39,192800.729710,87452.94
5,NK17LGF,1994:10:48,28.17,15:21:16,0.22,2028:29:46,28.65,3041:58:10,42.97,4038:01:50,57.03,8061,76617.81,123304.89,8026.93,36490.49,2711.04,9465.45,334983.01,458287.19,212486.885349,96382.43
6,NK17LGG,1880:42:28,28.70,22:25:46,0.34,2119:04:35,32.34,2529:47:11,38.61,4022:12:49,61.39,8738,64517.82,103831.82,7082.84,32199.35,2360.46,10397.63,302245.22,406076.38,187498.876863,85048.06
7,NK17LGJ,1818:51:17,28.07,05:08:19,0.08,2158:04:45,33.30,2497:55:39,38.55,3982:04:21,61.45,9895,58251.70,93747.56,6539.36,29728.61,2279.92,9385.80,304175.13,397921.98,173111.752153,78522.17
8,NK17LGL,1890:04:29,28.43,09:17:02,0.14,1872:18:52,28.16,2876:19:37,43.27,3771:40:23,56.73,8556,68870.85,110837.40,7280.34,33095.00,2511.80,8746.03,355323.17,466159.93,192714.484873,87413.82
9,NK67LKD,1855:46:17,28.32,05:40:41,0.09,2057:53:17,31.41,2632:39:45,40.18,3919:20:15,59.82,9501,66005.07,106225.44,7050.09,32050.50,2446.88,9143.92,265608.96,371833.69,186632.041295,84654.87
10,NK67LKE,1805:42:48,26.97,05:32:39,0.08,2310:05:24,34.50,2574:39:09,38.45,4121:20:51,61.55,10805,60797.79,97844.96,7202.29,32742.23,2245.45,10321.44,259980.10,357824.40,190660.900948,86482.33
11,NK67LKF,1830:26:58,27.84,01:06:19,0.02,2015:30:35,30.65,2728:56:08,41.50,3847:03:52,58.50,10148,63157.70,101642.87,6691.18,30418.70,2500.93,8942.85,282853.04,384495.18,177130.183942,80344.90
12,NK67LKX,1875:16:29,29.26,01:11:03,0.02,2015:19:52,31.45,2516:12:36,39.27,3891:47:24,60.73,9493,65315.45,105115.49,7000.38,31824.00,2400.22,8715.41,294726.18,399840.93,185313.147859,84056.63
13,NK67LKY,1771:19:07,26.36,10:00:16,0.15,1956:56:15,29.12,2981:44:22,44.37,3738:15:38,55.63,8326,61516.87,99002.35,7043.86,32022.32,2323.05,10093.07,275202.58,374204.20,186467.642586,84580.30
14,NK67LKZ,1693:03:12,25.65,00:50:39,0.01,2097:41:38,31.78,2808:24:31,42.55,3791:35:29,57.45,10226,55329.06,89043.84,6371.73,28966.29,2236.20,9712.86,264681.67,353724.79,168672.942924,76508.76
15,NK67LLA,1869:30:44,29.17,02:53:00,0.04,2160:23:33,33.71,2375:12:43,37.07,4032:47:17,62.93,9835,63107.72,101562.54,6960.82,31644.74,2306.55,9440.90,245380.45,346942.28,184269.413372,83583.20
16,NK67LLC,1839:43:43,27.48,03:50:36,0.06,2088:37:27,31.19,2763:48:14,41.28,3932:11:46,58.72,8826,64000.45,102999.36,6522.35,29650.86,2607.40,8699.07,274868.32,377867.00,172659.429731,78317.00
17,YM17NCA,731:49:40,26.75,16:34:16,0.61,1020:56:52,37.32,966:39:12,35.33,1769:20:48,64.67,2908,24766.07,39857.23,2769.02,12588.55,878.36,6208.05,437474.45,477331.40,73303.922577,33250.10

In [73]:
def duration_minutes(df): 
    df["UTILISATION_TIME"] = df["UTILISATION_TIME"].str.split(":").apply(lambda x: int(x[0]) * 60 + int(x[1]))
    return df

In [74]:
duration_minutes(df_annual)

,REG,DRIVING_TIME,DRIVING_PERC,IDLE_TIME,IDLE_PERC,STANDING_TIME,STANDING_PERC,INACTIVE_TIME,INACTIVE_PERC,UTILISATION_TIME,UTILISATION_PERC,JOURNEYS,MILES,KM,GALLONS,LITRES,MPG,L_100KM,ODOMETER_START,ODOMETER_END,CO2_LBS,CO2_KG
0,DX66OYU,1222:41:20,30.51,10:13:33,0.26,1587:20:09,39.60,1187:44:58,29.63,169215,70.37,6311,40179.07,64662.08,4592.16,20876.43,1391.39,7815.94,593088.25,657749.97,121565.294305,55141.09
1,DX66PFJ,710:14:58,36.54,02:31:54,0.13,654:45:06,33.68,576:28:02,29.65,82051,70.35,2747,27776.07,44701.41,2904.58,13204.25,728.78,3284.45,450256.78,494957.96,76889.300344,34876.40
2,KP63HZR,1911:32:27,29.61,07:00:02,0.11,2468:05:28,38.23,2069:22:03,32.05,263197,67.95,11539,59779.95,96206.93,7183.39,32654.50,2161.55,9818.92,399489.12,495695.40,190149.428500,86250.33
3,NK17LGD,1875:24:53,27.51,05:21:16,0.08,1933:03:51,28.36,3002:10:00,44.05,228830,55.95,8470,70040.09,112719.02,7866.50,35761.53,2447.39,10908.87,345915.39,458633.75,208241.928586,94456.95
4,NK17LGE,1801:27:33,27.29,05:49:52,0.09,2097:54:17,31.79,2694:48:18,40.83,234311,59.17,9674,61048.30,98248.16,7283.19,33109.87,2172.29,13364.21,351078.90,449326.39,192800.729710,87452.94
5,NK17LGF,1994:10:48,28.17,15:21:16,0.22,2028:29:46,28.65,3041:58:10,42.97,242281,57.03,8061,76617.81,123304.89,8026.93,36490.49,2711.04,9465.45,334983.01,458287.19,212486.885349,96382.43
6,NK17LGG,1880:42:28,28.70,22:25:46,0.34,2119:04:35,32.34,2529:47:11,38.61,241332,61.39,8738,64517.82,103831.82,7082.84,32199.35,2360.46,10397.63,302245.22,406076.38,187498.876863,85048.06
7,NK17LGJ,1818:51:17,28.07,05:08:19,0.08,2158:04:45,33.30,2497:55:39,38.55,238924,61.45,9895,58251.70,93747.56,6539.36,29728.61,2279.92,9385.80,304175.13,397921.98,173111.752153,78522.17
8,NK17LGL,1890:04:29,28.43,09:17:02,0.14,1872:18:52,28.16,2876:19:37,43.27,226300,56.73,8556,68870.85,110837.40,7280.34,33095.00,2511.80,8746.03,355323.17,466159.93,192714.484873,87413.82
9,NK67LKD,1855:46:17,28.32,05:40:41,0.09,2057:53:17,31.41,2632:39:45,40.18,235160,59.82,9501,66005.07,106225.44,7050.09,32050.50,2446.88,9143.92,265608.96,371833.69,186632.041295,84654.87
10,NK67LKE,1805:42:48,26.97,05:32:39,0.08,2310:05:24,34.50,2574:39:09,38.45,247280,61.55,10805,60797.79,97844.96,7202.29,32742.23,2245.45,10321.44,259980.10,357824.40,190660.900948,86482.33
11,NK67LKF,1830:26:58,27.84,01:06:19,0.02,2015:30:35,30.65,2728:56:08,41.50,230823,58.50,10148,63157.70,101642.87,6691.18,30418.70,2500.93,8942.85,282853.04,384495.18,177130.183942,80344.90
12,NK67LKX,1875:16:29,29.26,01:11:03,0.02,2015:19:52,31.45,2516:12:36,39.27,233507,60.73,9493,65315.45,105115.49,7000.38,31824.00,2400.22,8715.41,294726.18,399840.93,185313.147859,84056.63
13,NK67LKY,1771:19:07,26.36,10:00:16,0.15,1956:56:15,29.12,2981:44:22,44.37,224295,55.63,8326,61516.87,99002.35,7043.86,32022.32,2323.05,10093.07,275202.58,374204.20,186467.642586,84580.30
14,NK67LKZ,1693:03:12,25.65,00:50:39,0.01,2097:41:38,31.78,2808:24:31,42.55,227495,57.45,10226,55329.06,89043.84,6371.73,28966.29,2236.20,9712.86,264681.67,353724.79,168672.942924,76508.76
15,NK67LLA,1869:30:44,29.17,02:53:00,0.04,2160:23:33,33.71,2375:12:43,37.07,241967,62.93,9835,63107.72,101562.54,6960.82,31644.74,2306.55,9440.90,245380.45,346942.28,184269.413372,83583.20
16,NK67LLC,1839:43:43,27.48,03:50:36,0.06,2088:37:27,31.19,2763:48:14,41.28,235931,58.72,8826,64000.45,102999.36,6522.35,29650.86,2607.40,8699.07,274868.32,377867.00,172659.429731,78317.00
17,YM17NCA,731:49:40,26.75,16:34:16,0.61,1020:56:52,37.32,966:39:12,35.33,106160,64.67,2908,24766.07,39857.23,2769.02,12588.55,878.36,6208.05,437474.45,477331.40,73303.922577,33250.10

In [77]:
df_annual["util_min"] = df_annual["CO2_KG"] / df_annual["UTILISATION_TIME"] 
df_annual

,REG,DRIVING_TIME,DRIVING_PERC,IDLE_TIME,IDLE_PERC,STANDING_TIME,STANDING_PERC,INACTIVE_TIME,INACTIVE_PERC,UTILISATION_TIME,UTILISATION_PERC,JOURNEYS,MILES,KM,GALLONS,LITRES,MPG,L_100KM,ODOMETER_START,ODOMETER_END,CO2_LBS,CO2_KG,util_min
0,DX66OYU,1222:41:20,30.51,10:13:33,0.26,1587:20:09,39.60,1187:44:58,29.63,169215,70.37,6311,40179.07,64662.08,4592.16,20876.43,1391.39,7815.94,593088.25,657749.97,121565.294305,55141.09,0.325864
1,DX66PFJ,710:14:58,36.54,02:31:54,0.13,654:45:06,33.68,576:28:02,29.65,82051,70.35,2747,27776.07,44701.41,2904.58,13204.25,728.78,3284.45,450256.78,494957.96,76889.300344,34876.40,0.425058
2,KP63HZR,1911:32:27,29.61,07:00:02,0.11,2468:05:28,38.23,2069:22:03,32.05,263197,67.95,11539,59779.95,96206.93,7183.39,32654.50,2161.55,9818.92,399489.12,495695.40,190149.428500,86250.33,0.327703
3,NK17LGD,1875:24:53,27.51,05:21:16,0.08,1933:03:51,28.36,3002:10:00,44.05,228830,55.95,8470,70040.09,112719.02,7866.50,35761.53,2447.39,10908.87,345915.39,458633.75,208241.928586,94456.95,0.412782
4,NK17LGE,1801:27:33,27.29,05:49:52,0.09,2097:54:17,31.79,2694:48:18,40.83,234311,59.17,9674,61048.30,98248.16,7283.19,33109.87,2172.29,13364.21,351078.90,449326.39,192800.729710,87452.94,0.373234
5,NK17LGF,1994:10:48,28.17,15:21:16,0.22,2028:29:46,28.65,3041:58:10,42.97,242281,57.03,8061,76617.81,123304.89,8026.93,36490.49,2711.04,9465.45,334983.01,458287.19,212486.885349,96382.43,0.397813
6,NK17LGG,1880:42:28,28.70,22:25:46,0.34,2119:04:35,32.34,2529:47:11,38.61,241332,61.39,8738,64517.82,103831.82,7082.84,32199.35,2360.46,10397.63,302245.22,406076.38,187498.876863,85048.06,0.352411
7,NK17LGJ,1818:51:17,28.07,05:08:19,0.08,2158:04:45,33.30,2497:55:39,38.55,238924,61.45,9895,58251.70,93747.56,6539.36,29728.61,2279.92,9385.80,304175.13,397921.98,173111.752153,78522.17,0.328649
8,NK17LGL,1890:04:29,28.43,09:17:02,0.14,1872:18:52,28.16,2876:19:37,43.27,226300,56.73,8556,68870.85,110837.40,7280.34,33095.00,2511.80,8746.03,355323.17,466159.93,192714.484873,87413.82,0.386274
9,NK67LKD,1855:46:17,28.32,05:40:41,0.09,2057:53:17,31.41,2632:39:45,40.18,235160,59.82,9501,66005.07,106225.44,7050.09,32050.50,2446.88,9143.92,265608.96,371833.69,186632.041295,84654.87,0.359988
10,NK67LKE,1805:42:48,26.97,05:32:39,0.08,2310:05:24,34.50,2574:39:09,38.45,247280,61.55,10805,60797.79,97844.96,7202.29,32742.23,2245.45,10321.44,259980.10,357824.40,190660.900948,86482.33,0.349734
11,NK67LKF,1830:26:58,27.84,01:06:19,0.02,2015:30:35,30.65,2728:56:08,41.50,230823,58.50,10148,63157.70,101642.87,6691.18,30418.70,2500.93,8942.85,282853.04,384495.18,177130.183942,80344.90,0.348080
12,NK67LKX,1875:16:29,29.26,01:11:03,0.02,2015:19:52,31.45,2516:12:36,39.27,233507,60.73,9493,65315.45,105115.49,7000.38,31824.00,2400.22,8715.41,294726.18,399840.93,185313.147859,84056.63,0.359975
13,NK67LKY,1771:19:07,26.36,10:00:16,0.15,1956:56:15,29.12,2981:44:22,44.37,224295,55.63,8326,61516.87,99002.35,7043.86,32022.32,2323.05,10093.07,275202.58,374204.20,186467.642586,84580.30,0.377094
14,NK67LKZ,1693:03:12,25.65,00:50:39,0.01,2097:41:38,31.78,2808:24:31,42.55,227495,57.45,10226,55329.06,89043.84,6371.73,28966.29,2236.20,9712.86,264681.67,353724.79,168672.942924,76508.76,0.336310
15,NK67LLA,1869:30:44,29.17,02:53:00,0.04,2160:23:33,33.71,2375:12:43,37.07,241967,62.93,9835,63107.72,101562.54,6960.82,31644.74,2306.55,9440.90,245380.45,346942.28,184269.413372,83583.20,0.345432
16,NK67LLC,1839:43:43,27.48,03:50:36,0.06,2088:37:27,31.19,2763:48:14,41.28,235931,58.72,8826,64000.45,102999.36,6522.35,29650.86,2607.40,8699.07,274868.32,377867.00,172659.429731,78317.00,0.331949
17,YM17NCA,731:49:40,26.75,16:34:16,0.61,1020:56:52,37.32,966:39:12,35.33,106160,64.67,2908,24766.07,39857.23,2769.02,12588.55,878.36,6208.05,437474.45,477331.40,73303.922577,33250.10,0.313207

In [78]:
def emission(df, df2):
    for i in df["REG"]:
        for j in df2["REG"]:
            if i == j:
                df["CO2"] = df2["util_min"] * df["UTILISATION"]
            else:
                pass
    return df

In [79]:
emission(df, df_annual)

,REG,DATE,START,END,DRIVING_TIME,DRIVE_PERC,IDLE_TIME,IDLE_PERC,STANDING_TIME,STANDING_PERC,INACTIVE_TIME,INACTIVE_PERC,UTILISATION,UTILISATION_PERC,KM,LITRES,L_100KM,mileage,CO2
0,NK67LKY,2021-01-02,2021-02-01 04:10:00,2021-02-01 17:18:00,05:35:46,23.32,00:00:00,0.00,07:32:18,31.41,10:51:56,45.27,788,54.73,252.34,105.87,41.96,2.8939,256.780894
1,NK67LKF,2021-01-02,2021-02-01 05:22:00,2021-02-01 17:25:00,05:03:11,21.05,00:00:00,0.00,07:00:28,29.20,11:56:21,49.75,723,50.25,208.72,70.21,33.64,3.6120,307.316635
2,NK67LKZ,2021-01-02,2021-02-01 06:05:00,2021-02-01 19:30:00,07:33:36,31.50,00:00:12,0.01,05:50:50,24.36,10:35:22,44.12,804,55.88,423.01,120.62,28.52,4.2613,263.472856
3,NK67LKX,2021-01-02,2021-02-01 07:14:00,2021-02-02 00:00:00,06:45:06,28.13,00:00:39,0.05,09:59:47,41.65,07:14:28,30.17,1005,69.83,203.43,89.17,43.83,2.7692,414.846107
4,NK17LGJ,2021-01-02,2021-02-01 06:05:00,2021-02-01 19:16:00,07:37:08,31.75,00:00:00,0.00,05:33:14,23.14,10:49:38,45.11,790,54.89,426.99,104.15,24.39,4.9794,294.855225
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4491,NK67LKF,2021-12-31,2021-12-31 10:44:00,2021-12-31 10:58:00,00:05:17,0.37,00:07:23,0.51,00:01:13,0.08,23:46:07,99.04,13,0.96,0.35,1.09,315.36,0.3827,NaN
4492,NK67LKX,2021-12-31,2021-12-31 03:55:00,2021-12-31 14:16:00,05:46:55,24.09,00:01:42,0.12,04:32:11,18.90,13:39:12,56.89,620,43.11,246.95,84.57,34.25,3.5475,NaN
4493,NK67LKY,2021-12-31,2021-12-31 04:35:00,2021-12-31 12:54:00,03:53:17,16.20,00:06:04,0.42,04:20:09,18.07,15:40:30,65.31,499,34.69,264.31,102.08,38.62,3.1433,NaN
4494,KP63HZR,2021-12-31,2021-12-31 07:34:00,2021-12-31 10:51:00,00:51:26,3.57,00:00:00,0.00,02:25:07,10.08,20:43:27,86.35,196,13.65,20.62,11.50,55.77,2.1801,NaN
4495,YM17NCA,2021-12-31,2021-12-31 08:42:00,2021-12-31 12:06:00,00:27:24,1.90,00:36:05,2.51,02:20:38,9.77,20:35:53,85.83,204,14.17,3.92,3.88,99.03,1.2255,NaN

In [50]:
dfTransportJobs = pd.read_excel("../../HackathonNICD/Data/2. Transport jobs_2021.xlsx")
dfTransportJobs

,DRIVER,REG,TRL,DATE,JOB REF,CUSTOMER,ORDER No,J TYPE,WEIGHT,CONTAINER REF,TYPE,HAZ,COLLECT FROM,LOAD/DISCHARGE CUSTOMER,LOAD/DISCHARGE,DEL TIME,DELIVER TO
0,Port Driver_28,TUG,POT323XTL,2021-01-02,701954/ 1/D,TATA OUTBOUND,EMPTY PALLETS,CUR,NaN,NaN,NaN,-1,EAGLESCLIFFE,TETLEY,EAGLESCLIFFE,00:00:01,SOUTH SHIELDS
1,Port Driver_20,NK17LGD,POT-20-018,2021-01-02,700993/ 1/D,NISSAN MOTOR MANUFACTURING UK,1-1,IMP,NaN,AXIU1653829,40HC,-1,SOUTH SHIELDS,VANTEC KD IMPORTS,WASHINGTON,08:00:01,SOUTH SHIELDS
2,Port Driver_20,NK17LGD,POT-20-040,2021-01-02,701005/ 1/D,NISSAN MOTOR MANUFACTURING UK,1-3,IMP,NaN,MSKU1951479,40HC,-1,SOUTH SHIELDS,VANTEC KD IMPORTS,WASHINGTON,09:30:01,SOUTH SHIELDS
3,Port Driver_20,NK17LGD,POT323XTL,2021-01-02,700903/ 1/D,PORT OF TYNE AUTHORITY,STANDBY,CUR,NaN,NaN,NaN,-1,WALKER,WELLSTREAM / GE OIL & GAS,WALKER,10:30:01,SOUTH SHIELDS
4,Port Driver_20,NK17LGD,POT-20-011,2021-01-02,701945/ 1/D,OCEAN NETWORK EXPRESS PTE LTD,LIVA69945700,EXP,NaN,NYKU4332424,40HC,-1,SOUTH SHIELDS,ALDI DARLINGTON,DARLINGTON,11:00:00,SOUTH SHIELDS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20721,Agency driver_6,NK67LLC,POT-20-010,2021-12-31,725871/ 1/D,VIPA LAUSANNE SA,215325771,EXP,NaN,TGBU5356535,40HC,-1,SOUTH SHIELDS,HW MARTIN (PREMIER WASTE),WASHINGTON,10:00:01,SOUTH SHIELDS
20722,Subcontractor_12,V009,NaN,2021-12-31,725872/ 1/D,MAERSK A/S,213972944,IMP,NaN,MSKU7976411,20GP,-1,SOUTH SHIELDS,NIPPON EXPRESS WAREHOUSE,BOLDON,10:00:01,SOUTH SHIELDS
20723,Port Driver_33,NK67LLA,NaN,2021-12-31,725874/ 1/D,VIPA LAUSANNE SA,215296679,EXP,NaN,MSKU8618412,40HC,-1,SOUTH SHIELDS,J&B RECYCLING,HARTLEPOOL,10:00:01,SOUTH SHIELDS
20724,Subcontractor_7,K012,NaN,2021-12-31,725867/ 1/D,KUEHNE + NAGEL LTD,1042081017-1872,IMP,NaN,UACU5254495,40HC,-1,SOUTH SHIELDS,LANCHESTER WINES,FELLING,11:00:01,SOUTH SHIELDS
20725,Port Driver_12,NK17LGG,POT328XTL,2021-12-31,725946/ 1/D,Baker Hughes Energy Technology,POT03122021-3,CUR,NaN,NaN,NaN,-1,SOUTH SHIELDS,WELLSTREAM / GE OIL & GAS,WALKER,12:00:01,SOUTH SHIELDS

In [51]:
df["REG"].unique()

array(['NK17LGD', 'NK67LLA', 'NK17LGG', 'NK67LLC', 'NK67LKD', 'NK67LKY',
       'NK17LGL', 'NK67LKZ', 'NK67LKX', 'NK17LGE', 'NK17LGJ', 'NK17LGF',
       'NK67LKF', 'KP63HZR', 'NK67LKE', 'DX66OYU', 'YM17NCA', 'DX66PFJ'],
      dtype=object)

In [52]:
dfTransportJobs["REG"].unique()

array(['TUG', 'NK17LGD', 'NK17LGE', 'NK17LGF', 'NK67LKY', 'NK17LGJ',
       'NK17LGL', 'NK67LLA', 'NK67LKF', 'NK67LKE', 'NK67LKD', 'NK67LKX',
       'E012', 'NK17LGG', 'NK67LKZ', 'KP63HZR', 'S043', 'NK67LLC', 'O010',
       'DX660YU', 'G011', 'DX66PFJ', 'G012', 'KNO01', 'F002', 'V009',
       'DG67EGZ', nan, 'S035', 'P024', 'YM17NCA', 'K012', 'T032', 'KCL01'],
      dtype=object)

In [53]:
dfTransportJobs["REG"] = dfTransportJobs["REG"].replace({"DX660YU":"DX66OYU"})
dfTransportJobs.head(2)

,DRIVER,REG,TRL,DATE,JOB REF,CUSTOMER,ORDER No,J TYPE,WEIGHT,CONTAINER REF,TYPE,HAZ,COLLECT FROM,LOAD/DISCHARGE CUSTOMER,LOAD/DISCHARGE,DEL TIME,DELIVER TO
0,Port Driver_28,TUG,POT323XTL,2021-01-02,701954/ 1/D,TATA OUTBOUND,EMPTY PALLETS,CUR,NaN,NaN,NaN,-1,EAGLESCLIFFE,TETLEY,EAGLESCLIFFE,00:00:01,SOUTH SHIELDS
1,Port Driver_20,NK17LGD,POT-20-018,2021-01-02,700993/ 1/D,NISSAN MOTOR MANUFACTURING UK,1-1,IMP,NaN,AXIU1653829,40HC,-1,SOUTH SHIELDS,VANTEC KD IMPORTS,WASHINGTON,08:00:01,SOUTH SHIELDS

In [54]:
dfTransportJobs = dfTransportJobs.sort_values(by=['DATE'])
dfTransportJobs = dfTransportJobs.reset_index(drop = True)
dfTransportJobs

,DRIVER,REG,TRL,DATE,JOB REF,CUSTOMER,ORDER No,J TYPE,WEIGHT,CONTAINER REF,TYPE,HAZ,COLLECT FROM,LOAD/DISCHARGE CUSTOMER,LOAD/DISCHARGE,DEL TIME,DELIVER TO
0,Port Driver_28,TUG,POT323XTL,2021-01-02,701954/ 1/D,TATA OUTBOUND,EMPTY PALLETS,CUR,NaN,NaN,NaN,-1,EAGLESCLIFFE,TETLEY,EAGLESCLIFFE,00:00:01,SOUTH SHIELDS
1,Port Driver_20,NK17LGD,POT-20-018,2021-01-02,700993/ 1/D,NISSAN MOTOR MANUFACTURING UK,1-1,IMP,NaN,AXIU1653829,40HC,-1,SOUTH SHIELDS,VANTEC KD IMPORTS,WASHINGTON,08:00:01,SOUTH SHIELDS
2,Port Driver_20,NK17LGD,POT-20-040,2021-01-02,701005/ 1/D,NISSAN MOTOR MANUFACTURING UK,1-3,IMP,NaN,MSKU1951479,40HC,-1,SOUTH SHIELDS,VANTEC KD IMPORTS,WASHINGTON,09:30:01,SOUTH SHIELDS
3,Port Driver_20,NK17LGD,POT323XTL,2021-01-02,700903/ 1/D,PORT OF TYNE AUTHORITY,STANDBY,CUR,NaN,NaN,NaN,-1,WALKER,WELLSTREAM / GE OIL & GAS,WALKER,10:30:01,SOUTH SHIELDS
4,Port Driver_20,NK17LGD,POT-20-011,2021-01-02,701945/ 1/D,OCEAN NETWORK EXPRESS PTE LTD,LIVA69945700,EXP,NaN,NYKU4332424,40HC,-1,SOUTH SHIELDS,ALDI DARLINGTON,DARLINGTON,11:00:00,SOUTH SHIELDS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20721,Port Driver_14,NK67LKE,FAC31207,2021-12-31,726019/ 1/D,TATA OUTBOUND,POTL26394,CUR,NaN,NaN,NaN,-1,SOUTH SHIELDS,TETLEY,EAGLESCLIFFE,06:30:01,SOUTH SHIELDS
20722,Port Driver_14,NK67LKE,NaN,2021-12-31,726053/ 1/D,TATA INBOUND FINISHED,STOCK TRANSFER,CUR,NaN,NaN,NaN,-1,EAGLESCLIFFE,TETLEY,EAGLESCLIFFE,06:31:01,SOUTH SHIELDS
20723,Subcontractor_12,V009,NaN,2021-12-31,725879/ 1/D,NIPPON EXPRESS (UK) LIMITED,NOI-07926,IMP,NaN,BMOU2423338,20GP,-1,SOUTH SHIELDS,NIPPON EXPRESS WAREHOUSE,BOLDON,07:00:01,SOUTH SHIELDS
20724,Port Driver_24,NK67LKY,FAC31136,2021-12-31,726016/ 1/D,TATA OUTBOUND,POTL26392K/INFRE_9_3,CUR,NaN,NaN,NaN,-1,SOUTH SHIELDS,TETLEY,EAGLESCLIFFE,05:30:01,SOUTH SHIELDS
20725,Port Driver_12,NK17LGG,POT328XTL,2021-12-31,725946/ 1/D,Baker Hughes Energy Technology,POT03122021-3,CUR,NaN,NaN,NaN,-1,SOUTH SHIELDS,WELLSTREAM / GE OIL & GAS,WALKER,12:00:01,SOUTH SHIELDS

In [12]:
dfTransportJobs.DATE.min(), dfTransportJobs.DATE.max()

(Timestamp('2021-01-02 00:00:00'), Timestamp('2021-12-31 00:00:00'))

In [28]:
dfTransportJobs["REG"].unique()

array(['TUG', 'NK17LGD', 'NK17LGE', 'NK67LLA', 'NK67LKE', 'E012',
       'NK67LKY', 'NK67LKX', 'NK17LGJ', 'NK17LGG', 'NK67LKZ', 'NK17LGF',
       'NK17LGL', 'NK67LKF', 'NK67LKD', 'S043', 'KP63HZR', 'NK67LLC',
       'O010', 'DX660YU', 'DX66PFJ', 'G011', 'G012', 'KNO01', 'F002',
       'V009', 'DG67EGZ', nan, 'S035', 'P024', 'YM17NCA', 'K012', 'T032',
       'KCL01'], dtype=object)

In [30]:
unique = df["REG"].unique()
unique

array(['NK17LGD', 'NK67LLA', 'NK17LGG', 'NK67LLC', 'NK67LKD', 'NK67LKY',
       'NK17LGL', 'NK67LKZ', 'NK67LKX', 'NK17LGE', 'NK17LGJ', 'NK17LGF',
       'NK67LKF', 'KP63HZR', 'NK67LKE', 'DX66OYU', 'YM17NCA', 'DX66PFJ'],
      dtype=object)

In [46]:
dfTransportJobs = dfTransportJobs[~dfTransportJobs.REG.isin(unique)]
dfTransportJobs

,DRIVER,REG,TRL,DATE,JOB REF,CUSTOMER,ORDER No,J TYPE,WEIGHT,CONTAINER REF,TYPE,HAZ,COLLECT FROM,LOAD/DISCHARGE CUSTOMER,LOAD/DISCHARGE,DEL TIME,DELIVER TO
0,Port Driver_28,TUG,POT323XTL,2021-01-02,701954/ 1/D,TATA OUTBOUND,EMPTY PALLETS,CUR,NaN,NaN,NaN,-1,EAGLESCLIFFE,TETLEY,EAGLESCLIFFE,00:00:01,SOUTH SHIELDS
16,Subcontractor_2,E012,NaN,2021-01-04,701955/ 1/D,TATA OUTBOUND,81000343,CUR,NaN,NaN,NaN,-1,SOUTH SHIELDS,CULLINA,SALFORD,12:00:01,SOUTH SHIELDS
45,Port Driver_28,TUG,POT319XTL,2021-01-04,701383/ 1/D,JML DIRECT LTD,JML/04/01/21,CUR,NaN,NaN,NaN,-1,SOUTH SHIELDS,JML DIRECT - UNIT 1,SOUTH SHIELDS,08:00:00,SOUTH SHIELDS
60,Subcontractor_10,S043,NaN,2021-01-05,701989/ 1/D,MAERSK A/S,206789327,IMP,NaN,UETU5038166,40HC,-1,SOUTH SHIELDS,PALRAM DPL LTD,NEWTON AYCLIFFE,11:00:00,SOUTH SHIELDS
93,Subcontractor_1,O010,NaN,2021-01-05,701950/ 1/D,MAERSK A/S,206916435,EXP,NaN,MRKU6632929,20GP,-1,SOUTH SHIELDS,J DENHAM METALS LTD,BISHOP AUCKLAND,10:30:00,SOUTH SHIELDS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20714,Subcontractor_1,O010,NaN,2021-12-31,726156/ 1/D,MAERSK A/S,PO372732,MT,NaN,MRKU5506783,40HC,-1,TEESPORT,TEESPORT,TEESPORT,00:00:01,SOUTH SHIELDS
20715,Subcontractor_6,G012,NaN,2021-12-31,726162/ 1/D,MAERSK A/S,PO372732,MT,NaN,WCIU8099134,40HC,-1,TEESPORT,TEESPORT,TEESPORT,00:00:01,SOUTH SHIELDS
20716,Subcontractor_1,O010,NaN,2021-12-31,725296/ 1/D,OCEAN NETWORK EXPRESS PTE LTD,LIVB67690300,EXP,NaN,CAIU8981810,40HC,-1,SOUTH SHIELDS,Teeside Biffa Waste Services L,HARTLEPOOL,08:00:00,SOUTH SHIELDS
20719,Subcontractor_7,K012,NaN,2021-12-31,725869/ 1/D,KUEHNE + NAGEL LTD,1041758842-1872,IMP,NaN,UACU8514723,40HC,-1,SOUTH SHIELDS,LANCHESTER WINES,FELLING,06:00:01,SOUTH SHIELDS
20723,Subcontractor_12,V009,NaN,2021-12-31,725879/ 1/D,NIPPON EXPRESS (UK) LIMITED,NOI-07926,IMP,NaN,BMOU2423338,20GP,-1,SOUTH SHIELDS,NIPPON EXPRESS WAREHOUSE,BOLDON,07:00:01,SOUTH SHIELDS

In [37]:
dfTransportJobs["REG"].unique()

array(['TUG', 'E012', 'S043', 'O010', 'DX660YU', 'G011', 'G012', 'KNO01',
       'F002', 'V009', 'DG67EGZ', nan, 'S035', 'P024', 'K012', 'T032',
       'KCL01'], dtype=object)

In [ ]:
for i in df["REG"]:

In [26]:
def merge_clean(df1, df2, key):
    
    df_merged = pd.merge(df1, df2, how="inner", on = key)
    
    for col in df_merged.columns:
        if col.endswith("_x"):
            df_merged.rename(columns = lambda col:col.rstrip("_x"), inplace = True)
        elif col.endswith("_y"):
            to_drop = [col for col in df_merged if col.endswith("_y")]
            df_merged.drop(to_drop, axis = 1, inplace = True)
        else:
            pass
    return df_merged

In [27]:
df_merge = merge_clean(df, dfTransportJobs, "REG")
df_merge

,REG,DATE,START,END,DRIVING_TIME,DRIVE_PERC,IDLE_TIME,IDLE_PERC,STANDING_TIME,STANDING_PERC,INACTIVE_TIME,INACTIVE_PERC,UTILISATION,UTILISATION_PERC,KM,LITRES,L_100KM,mileage,DRIVER,TRL,JOB REF,CUSTOMER,ORDER No,J TYPE,WEIGHT,CONTAINER REF,TYPE,HAZ,COLLECT FROM,LOAD/DISCHARGE CUSTOMER,LOAD/DISCHARGE,DEL TIME,DELIVER TO
0,NK17LGD,2021-01-02,2021-02-01 04:59:00,2021-02-01 15:35:00,05:21:59,22.36,00:00:00,0.0,05:14:41,21.85,13:23:20,55.79,10:36:40,44.21,354.17,89.03,25.14,4.8332,Port Driver_20,POT-20-018,700993/ 1/D,NISSAN MOTOR MANUFACTURING UK,1-1,IMP,NaN,AXIU1653829,40HC,-1,SOUTH SHIELDS,VANTEC KD IMPORTS,WASHINGTON,08:00:01,SOUTH SHIELDS
1,NK17LGD,2021-01-02,2021-02-01 04:59:00,2021-02-01 15:35:00,05:21:59,22.36,00:00:00,0.0,05:14:41,21.85,13:23:20,55.79,10:36:40,44.21,354.17,89.03,25.14,4.8332,Port Driver_20,POT-20-040,701005/ 1/D,NISSAN MOTOR MANUFACTURING UK,1-3,IMP,NaN,MSKU1951479,40HC,-1,SOUTH SHIELDS,VANTEC KD IMPORTS,WASHINGTON,09:30:01,SOUTH SHIELDS
2,NK17LGD,2021-01-02,2021-02-01 04:59:00,2021-02-01 15:35:00,05:21:59,22.36,00:00:00,0.0,05:14:41,21.85,13:23:20,55.79,10:36:40,44.21,354.17,89.03,25.14,4.8332,Port Driver_20,POT323XTL,700903/ 1/D,PORT OF TYNE AUTHORITY,STANDBY,CUR,NaN,NaN,NaN,-1,WALKER,WELLSTREAM / GE OIL & GAS,WALKER,10:30:01,SOUTH SHIELDS
3,NK17LGD,2021-01-02,2021-02-01 04:59:00,2021-02-01 15:35:00,05:21:59,22.36,00:00:00,0.0,05:14:41,21.85,13:23:20,55.79,10:36:40,44.21,354.17,89.03,25.14,4.8332,Port Driver_20,POT-20-011,701945/ 1/D,OCEAN NETWORK EXPRESS PTE LTD,LIVA69945700,EXP,NaN,NYKU4332424,40HC,-1,SOUTH SHIELDS,ALDI DARLINGTON,DARLINGTON,11:00:00,SOUTH SHIELDS
4,NK17LGD,2021-01-02,2021-02-01 04:59:00,2021-02-01 15:35:00,05:21:59,22.36,00:00:00,0.0,05:14:41,21.85,13:23:20,55.79,10:36:40,44.21,354.17,89.03,25.14,4.8332,Port Driver_20,POT-20-037,700989/ 1/D,NISSAN MOTOR MANUFACTURING UK,1-4,IMP,NaN,DFSU7378249,40HC,-1,SOUTH SHIELDS,VANTEC KD IMPORTS,WASHINGTON,11:00:01,SOUTH SHIELDS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4108434,DX66PFJ,2021-12-30,2021-12-30 14:54:00,2021-12-30 15:56:00,00:20:54,1.45,00:00:00,0.0,00:41:09,2.86,22:57:57,95.69,01:02:03,4.31,3.61,2.78,77.23,1.5738,Agency driver_10,POT-20-026,725631/ 1/D,FITFLOP LTD,376540,IMP,NaN,FCLU9429747,40GP,-1,SOUTH SHIELDS,WHISTL FULFILMENT (UNIT 1),GATESHEAD,13:00:01,SOUTH SHIELDS
4108435,DX66PFJ,2021-12-30,2021-12-30 14:54:00,2021-12-30 15:56:00,00:20:54,1.45,00:00:00,0.0,00:41:09,2.86,22:57:57,95.69,01:02:03,4.31,3.61,2.78,77.23,1.5738,Agency driver_10,POT-20-026,725625/ 1/D,KUEHNE + NAGEL LTD,1042007119-1872,IMP,NaN,FCIU6487684,20GP,-1,SOUTH SHIELDS,GREENCROFT BOTTLING,UNIT6 THE GROVE IND EST CONSET,10:00:01,SOUTH SHIELDS
4108436,DX66PFJ,2021-12-30,2021-12-30 14:54:00,2021-12-30 15:56:00,00:20:54,1.45,00:00:00,0.0,00:41:09,2.86,22:57:57,95.69,01:02:03,4.31,3.61,2.78,77.23,1.5738,Agency driver_10,POT-20-026,725728/ 1/D,HAPAG LLOYD AG,79385151-001,EXP,NaN,HLBU1801204,40GP,-1,SOUTH SHIELDS,THOMAS SWANN & CO LTD,CONSETT,12:00:01,SOUTH SHIELDS
4108437,DX66PFJ,2021-12-30,2021-12-30 14:54:00,2021-12-30 15:56:00,00:20:54,1.45,00:00:00,0.0,00:41:09,2.86,22:57:57,95.69,01:02:03,4.31,3.61,2.78,77.23,1.5738,Agency driver_10,POT-20-026,725692/ 1/D,VIPA LAUSANNE SA,215074149,EXP,NaN,MRKU5512111,40HC,-1,SOUTH SHIELDS,BIFFA WALLSEND,WALLSEND,09:00:01,SOUTH SHIELDS
4108438,DX66PFJ,2021-12-30,2021-12-30 14:54:00,2021-12-30 15:56:00,00:20:54,1.45,00:00:00,0.0,00:41:09,2.86,22:57:57,95.69,01:02:03,4.31,3.61,2.78,77.23,1.5738,Agency driver_10,POT120STD,724877/ 1/D,J BARBOUR AND SONS LTD,SHUNTING,CUR,NaN,NaN,NaN,-1,SOUTH SHIELDS,J BARBOUR & SONS LTD,JARROW,08:00:01,SOUTH SHIELDS